SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[KPI_DIMENSION]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[KPI_DIMENSION] (
	[KPI_Id] int IDENTITY(1, 1) NOT NULL,
	[KPI_Desc] nvarchar(50) NULL,
	[Fact] nvarchar(50) NULL,
CONSTRAINT [PK_KPI_DIMENSION]
	PRIMARY KEY NONCLUSTERED ([KPI_Id]))
END
GO
