SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[OpsDB_DowntimeUptime_Data]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[OpsDB_DowntimeUptime_Data] (
	[CentralRcdIdx] bigint IDENTITY(1, 1) NOT NULL,
	[StartTime] datetime NULL,
	[EndTime] datetime NULL,
	[StartTimeUTC] datetimeoffset(7) NULL,
	[EndTimeUTC] datetimeoffset(7) NULL,
	[Duration] decimal(12, 3) NULL,
	[Total_Uptime] float NULL,
	[Uptime] decimal(12, 3) NULL,
	[Fault] varchar(100) NULL,
	[FaultGlobal] varchar(100) NULL,
	[FaultCode] varchar(30) NULL,
	[Reason1Id] int NULL,
	[Reason1] varchar(100) NULL,
	[Reason1Global] varchar(100) NULL,
	[Reason1Code] varchar(30) NULL,
	[Reason1Category] nvarchar(4000) NULL,
	[Reason1CategoryGlobal] nvarchar(4000) NULL,
	[Reason2Id] int NULL,
	[Reason2] varchar(100) NULL,
	[Reason2Global] varchar(100) NULL,
	[Reason2Code] varchar(30) NULL,
	[Reason2Category] nvarchar(4000) NULL,
	[Reason2CategoryGlobal] nvarchar(4000) NULL,
	[Reason3Id] int NULL,
	[Reason3] varchar(100) NULL,
	[Reason3Global] varchar(100) NULL,
	[Reason3Code] varchar(30) NULL,
	[Reason3Category] nvarchar(4000) NULL,
	[Reason3CategoryGlobal] nvarchar(4000) NULL,
	[Reason4Id] int NULL,
	[Reason4] varchar(100) NULL,
	[Reason4Global] varchar(100) NULL,
	[Reason4Code] varchar(30) NULL,
	[Reason4Category] nvarchar(4000) NULL,
	[Reason4CategoryGlobal] nvarchar(4000) NULL,
	[Action1] varchar(100) NULL,
	[Action1Code] varchar(30) NULL,
	[Action2] varchar(100) NULL,
	[Action2Code] varchar(30) NULL,
	[Action3] varchar(100) NULL,
	[Action3Code] varchar(30) NULL,
	[Action4] varchar(100) NULL,
	[Action4Code] varchar(30) NULL,
	[Planned] bit NULL,
	[DChangeOverAlltypes] bit NULL,
	[DChangeOverPackingCO] bit NULL,
	[Location] varchar(100) NULL,
	[LocationGlobal] varchar(100) NULL,
	[ProdDesc] nvarchar(255) NULL,
	[ProdDescGlobal] varchar(50) NULL,
	[ProdCode] varchar(25) NULL,
	[ProdFam] nvarchar(100) NULL,
	[ProdGroup] nvarchar(100) NULL,
	[ProdGroupGlobal] varchar(50) NULL,
	[ProcessOrder] nvarchar(50) NULL,
	[TeamDesc] varchar(25) NULL,
	[ShiftDesc] varchar(25) NULL,
	[LineStatus] nvarchar(50) NULL,
	[DTStatus] int NULL,
	[Comments] nvarchar(1000) NULL,
	[MainComments] nvarchar(1000) NULL,
	[PLDesc] varchar(100) NULL,
	[PUDesc] varchar(200) NULL,
	[PLDescGlobal] varchar(50) NULL,
	[PUDescGlobal] varchar(50) NULL,
	[PUID] int NULL,
	[PLID] int NULL,
	[BreakDown] bit NULL,
	[ProcFailure] bit NULL,
	[TransferFlag] int NULL,
	[DeleteFlag] bit NOT NULL,
	[Site] varchar(50) NULL,
	[TEDetId] int NOT NULL,
	[Ts] datetime NULL,
	[IsContraint] bit NULL,
	[ProductionDay] date NULL,
	[IsStarved] bit NULL,
	[IsBlocked] bit NULL,
	[ManualStops] bit NOT NULL,
	[MinorStop] int NULL,
	[MajorStop] int NULL,
	[ZoneDesc] nvarchar(255) NULL,
	[ZoneGrpDesc] nvarchar(255) NULL,
	[LineGroup] nvarchar(255) NULL,
	[StopsEquipFails] int NULL,
	[StopsELP] int NULL,
	[StopsScheduled] int NULL,
	[StopsUnscheduled] int NULL,
	[StopsUnscheduledInternal] int NULL,
	[StopsUnscheduledBS] int NULL,
	[StopsBlockedStarved] int NULL,
	[ERTD_ID] int NULL,
	[RawRateloss] float NULL,
	[RateLossRatio] float NULL,
	[CommentId] int NULL,
	[CommentModifOn] datetime NULL,
	[Comment_Rtf] text NULL,
	[SITE_DIMENSION_SiteId] int NOT NULL,
	[LINE_DIMENSION_CentralLineId] int NOT NULL,
	[RcdIdx] int NOT NULL,
	[Repulper_Tons] decimal(12, 3) NULL,
CONSTRAINT [FK_OpsDB_DowntimeUptime_Data_LINE_DIMENSION]
	FOREIGN KEY ([LINE_DIMENSION_CentralLineId])
	REFERENCES [dbo].[LINE_DIMENSION] ([CentralLineId]),
CONSTRAINT [FK_OpsDB_DowntimeUptime_Data_SITE_DIMENSION]
	FOREIGN KEY ([SITE_DIMENSION_SiteId])
	REFERENCES [dbo].[SITE_DIMENSION] ([SiteId]),
CONSTRAINT [PK_OpsDB_DowntimeUptime_Data]
	PRIMARY KEY NONCLUSTERED ([CentralRcdIdx]))
END
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[OpsDB_DowntimeUptime_Data]') AND name = N'IDX_UQ_OpsDB_DowntimeUptime_Data_SiteId_RcdIdx')
	CREATE UNIQUE NONCLUSTERED INDEX [IDX_UQ_OpsDB_DowntimeUptime_Data_SiteId_RcdIdx] ON [dbo].[OpsDB_DowntimeUptime_Data]
		([SITE_DIMENSION_SiteId], [RcdIdx])
GO
