
GO

--DROP TYPE [dbo].[OpsDB_Production_Data_PM_Type]
GO

/****** Object:  UserDefinedTableType [dbo].[OpsDB_Production_Data_PM_Type]    Script Date: 9/1/2020 2:56:17 PM ******/
CREATE TYPE [dbo].[OpsDB_Production_Data_PM_Type] AS TABLE(
	[DataServerName] [varchar](100) NULL,
	[StartTime] [datetime] NULL,
	[EndTime] [datetime] NULL,
	[StartTimeUTC] [datetimeoffset](7) NULL,
	[EndTimeUTC] [datetimeoffset](7) NULL,
	[Site] [varchar](50) NULL,
	[PLID] [int] NULL,
	[PLDesc] [varchar](75) NULL,
	[PUID] [int] NULL,
	[PUDesc] [varchar](200) NULL,
	[ProdId] [int] NULL,
	[ProdCode] [varchar](50) NULL,
	[ProdDesc] [varchar](255) NULL,
	[ProdFam] [varchar](100) NULL,
	[ProdGroup] [varchar](100) NULL,
	[ShiftDesc] [varchar](50) NULL,
	[TeamDesc] [varchar](50) NULL,
	[NPTStatus] [varchar](50) NULL,
	[ProcessOrder] [varchar](50) NULL,
	[ProductTime] [decimal](10, 2) NULL,
	[GoodTons] [decimal](10, 3) NULL,
	[RejectTons] [decimal](10, 3) NULL,
	[HoldTons] [decimal](10, 3) NULL,
	[FireTons] [decimal](10, 3) NULL,
	[TAYTons] [decimal](10, 3) NULL,
	[SlabTons] [decimal](10, 3) NULL,
	[RepulperTons] [decimal](10, 3) NULL,
	[TeardownTons] [decimal](10, 3) NULL,
	[RATons] [decimal](10, 3) NULL,
	[TotalTons] [decimal](10, 3) NULL,
	[UnExpTons] [decimal](10, 3) NULL,
	[GoodRolls] [int] NULL,
	[RejectRolls] [int] NULL,
	[HoldRolls] [int] NULL,
	[FireRolls] [int] NULL,
	[LastCleaningBlades] [DATETIME] NULL,
	[LastCrepingBlades] [DATETIME] NULL,
	[LifeCrepingBlades] [FLOAT] NULL,
	[LifeCleaningBlades] [FLOAT] NULL,
	[CleaningBlades] [int] NULL,
	[CrepingBlades] [int] NULL,
	[Sheetbreaks] [int] NULL,
	[SheetbreaksTime] [decimal](10, 2) NULL,
	[Stops] [int] NULL,
	[YankeeSpeedSum] [decimal](10, 2) NULL,
	[YankeeSpeedCount] [int] NULL,
	[ReelSpeedSum] [decimal](10, 2) NULL,
	[ReelSpeedCount] [int] NULL,
	[FormingWireLife] [decimal](10, 2) NULL,
	[BackingWireLife] [decimal](10, 2) NULL,
	[BeltLife] [decimal](10, 2) NULL,
	[Belt_Id] [varchar](20) NULL,
	[T3rd_Furnish_Sum] [float] NULL,
	[CTMP_Sum] [float] NULL,
	[Fiber_1_Sum] [float] NULL,
	[Fiber_2_Sum] [float] NULL,
	[Long_Fiber_Sum] [float] NULL,
	[Machine_Broke_Sum] [float] NULL,
	[Product_Broke_Sum] [float] NULL,
	[Short_Fiber_Sum] [float] NULL,
	[Absorb_Aid_Towel_Sum] [float] NULL,
	[Aloe_E_Additive_Sum] [float] NULL,
	[Biocide_Sum] [float] NULL,
	[Cat_Promoter_Sum] [float] NULL,
	[Chem_1_Sum] [float] NULL,
	[Chem_2_Sum] [float] NULL,
	[Chlorine_Control_Sum] [float] NULL,
	[Defoamer_Sum] [float] NULL,
	[Dry_Strength_Facial_Sum] [float] NULL,
	[Dry_Strength_Tissue_Sum] [float] NULL,
	[Recycle_Fiber_Sum] [float] NULL,
	[Dry_Strength_Towel_Sum] [float] NULL,
	[Dye_1_Sum] [float] NULL,
	[Dye_2_Sum] [float] NULL,
	[Emulsion_1_Sum] [float] NULL,
	[Emulsion_2_Sum] [float] NULL,
	[Flocculant_Sum] [float] NULL,
	[Glue_Adhesive_Sum] [float] NULL,
	[Glue_Crepe_Aid_Sum] [float] NULL,
	[Glue_Release_Aid_Sum] [float] NULL,
	[Glue_Total_Sum] [float] NULL,
	[pH_Control_Tissue_Acid_Sum] [float] NULL,
	[pH_Control_Towel_Base_Sum] [float] NULL,
	[Single_Glue_Sum] [float] NULL,
	[Softener_Facial_Sum] [float] NULL,
	[Softener_Tissue_Sum] [float] NULL,
	[Softener_Towel_Sum] [float] NULL,
	[Wet_Strength_Facial_Sum] [float] NULL,
	[Wet_Strength_Tissue_Sum] [float] NULL,
	[Wet_Strength_Towel_Sum] [float] NULL,
	[Air_Sum] [float] NULL,
	[Air_UOM] [nvarchar](15) NULL,
	[Air_Per_YKT] [float] NULL,
	[Electric_Sum] [float] NULL,
	[Electric_UOM] [nvarchar](15) NULL,
	[Electric_Per_YKT] [float] NULL,
	[Gas_Sum] [float] NULL,
	[Gas_UOM] [nvarchar](15) NULL,
	[Gas_Per_YKT] [float] NULL,
	[Steam_Sum] [float] NULL,
	[Steam_UOM] [nvarchar](15) NULL,
	[Steam_Per_YKT] [float] NULL,
	[Water_Sum] [float] NULL,
	[Water_UOM] [nvarchar](15) NULL,
	[Water_Per_YKT] [float] NULL,
	[GRHF_Tons] [decimal](10, 3) NULL,
	[All_Tons] [decimal](10, 3) NULL,
	[All_Furnish] [decimal](10, 3) NULL,
	[All_Furnish_Perc_Calc] [decimal](10, 3) NULL,
	[Total_Roll_Status_Cnt] [float] NULL,
	[Ts] [datetime] NULL,
	[DeleteFlag] [bit] NOT NULL,
	[GI_Downtime] [decimal](10, 2) NULL,
	[GE_Downtime] [decimal](10, 2) NULL,
	[GI_Uptime] [decimal](10, 2) NULL,
	[GE_Uptime] [decimal](10, 2) NULL,
	[RcdIdx] [bigint] NOT NULL,
	PRIMARY KEY CLUSTERED 
(
	[RcdIdx] ASC
)WITH (IGNORE_DUP_KEY = OFF)
)
GO
