DROP PROCEDURE splocal_InsertProductionRawDataCvtg
DROP PROCEDURE splocal_InsertProductionRawDataCvtg
GO

CREATE PROCEDURE splocal_InsertProductionRawDataCvtg
  @ProductionRawdataCvtg [dbo].[OpsDB_Production_Data_Cvtg_Type] READONLY
AS
	DECLARE @SiteId INTEGER

	SELECT TOP 1 @SiteId = sd.SiteId
	FROM @ProductionRawdataCvtg dtd
	JOIN SITE_DIMENSION sd ON dtd.DataServerName = sd.DataServerName

	INSERT INTO dbo.OpsDB_Production_Data_Cvtg (
		[SITE],
		[ProcessOrder],
		[PLId],
		[PUId],
		[EventId],
		[StartTime],
		[EndTime],
		[StartTimeUTC],
		[EndTimeUTC],
		[ProdId],
		[PLDesc],
		[ReliabilityPUID],
		[PUDesc],
		[ShiftDesc],
		[TeamDesc],
		[ProdCode],
		[ProdDesc],
		[ProdFamily],
		[ProdGroup],
		[PPId],
		[POStatus],
		[PPStatusId],
		[BatchNumber],
		[TotalUnits],
		[GoodUnits],
		[RejectUnits],
		[WebWidth],
		[SheetWidth],
		[LineSpeedIdeal],
		[LineSpeedTarget],
		[LineSpeedAvg],
		[TargetLineSpeed],
		[LineStatus],
		[RollsPerLog],
		[RollsInPack],
		[PacksInBundle],
		[CartonsInCase],
		[SheetCount],
		[ShipUnit],
		[CalendarRuntime],
		[ProductionRuntime],
		[PlanningRuntime],
		[OperationsRuntime],
		[SheetLength],
		[StatFactor],
		[TargetUnits],
		[ActualUnits],
		[OperationsTargetUnits],
		[HolidayCurtailDT],
		[PlninterventionDT],
		[ChangeOverDT],
		[HygCleaningDT],
		[EOProjectsDT],
		[UnscheduledDT],
		[CLAuditsDT],
		[IdealUnits],
		[RollWidth2Stage],
		[RollWidth3Stage],
		[SplitUptime],
		[Runtime],
		[CnvtLineSpeedToSheetLength],
		[CnvtParentRollWidthToSheetWidth],
		[DefaultPMRollWidth],
		[LineSpeedUOM],
		[SheetLengthSpec],
		[SheetLengthSpecUOM],
		[SheetWidthSpec],
		[SheetWidthSpecUOM],
		[PlannedRejectLogs],
		[UnplannedRejectLogs],
		[BreakoutRejectLogs],
		[ManualRejectLogs],
		[OtherRejectLogs],
		[ILOCSetpointTarget],
		[ILOCSetpointAverage],
		[ILOCSetpointSampleCount],
		[ILOCActualAverage],
		[ILOCActualSampleCount],
		[ts],
		[deleteflag],
		[RcdIdx],
		[SITE_DIMENSION_SiteId],
		[LINE_DIMENSION_CentralLineId]
	)
	SELECT
		prd.[SITE],
		prd.[ProcessOrder],
		prd.[PLId],
		prd.[PUId],
		prd.[EventId],
		prd.[StartTime],
		prd.[EndTime],
		prd.[StartTimeUTC],
		prd.[EndTimeUTC],
		prd.[ProdId],
		prd.[PLDesc],
		prd.[ReliabilityPUID],
		prd.[PUDesc],
		prd.[ShiftDesc],
		prd.[TeamDesc],
		prd.[ProdCode],
		prd.[ProdDesc],
		prd.[ProdFamily],
		prd.[ProdGroup],
		prd.[PPId],
		prd.[POStatus],
		prd.[PPStatusId],
		prd.[BatchNumber],
		prd.[TotalUnits],
		prd.[GoodUnits],
		prd.[RejectUnits],
		prd.[WebWidth],
		prd.[SheetWidth],
		prd.[LineSpeedIdeal],
		prd.[LineSpeedTarget],
		prd.[LineSpeedAvg],
		prd.[TargetLineSpeed],
		prd.[LineStatus],
		prd.[RollsPerLog],
		prd.[RollsInPack],
		prd.[PacksInBundle],
		prd.[CartonsInCase],
		prd.[SheetCount],
		prd.[ShipUnit],
		prd.[CalendarRuntime],
		prd.[ProductionRuntime],
		prd.[PlanningRuntime],
		prd.[OperationsRuntime],
		prd.[SheetLength],
		prd.[StatFactor],
		prd.[TargetUnits],
		prd.[ActualUnits],
		prd.[OperationsTargetUnits],
		prd.[HolidayCurtailDT],
		prd.[PlninterventionDT],
		prd.[ChangeOverDT],
		prd.[HygCleaningDT],
		prd.[EOProjectsDT],
		prd.[UnscheduledDT],
		prd.[CLAuditsDT],
		prd.[IdealUnits],
		prd.[RollWidth2Stage],
		prd.[RollWidth3Stage],
		prd.[SplitUptime],
		prd.[Runtime],
		prd.[CnvtLineSpeedToSheetLength],
		prd.[CnvtParentRollWidthToSheetWidth],
		prd.[DefaultPMRollWidth],
		prd.[LineSpeedUOM],
		prd.[SheetLengthSpec],
		prd.[SheetLengthSpecUOM],
		prd.[SheetWidthSpec],
		prd.[SheetWidthSpecUOM],
		prd.[PlannedRejectLogs],
		prd.[UnplannedRejectLogs],
		prd.[BreakoutRejectLogs],
		prd.[ManualRejectLogs],
		prd.[OtherRejectLogs],
		prd.[ILOCSetpointTarget],
		prd.[ILOCSetpointAverage],
		prd.[ILOCSetpointSampleCount],
		prd.[ILOCActualAverage],
		prd.[ILOCActualSampleCount],
		prd.[ts],
		prd.[deleteflag],
		prd.[RcdIdx],
		@SiteId AS SITE_DIMENSION_SiteId,
		ld.CentralLineId AS LINE_DIMENSION_CentralLineId
		FROM  @ProductionRawdataCvtg prd
		JOIN dbo.LINE_DIMENSION ld ON prd.PLID = ld.PLId AND ld.SITE_DIMENSION_SiteId = @SiteId
		WHERE NOT EXISTS (  SELECT *
							FROM dbo.OpsDB_Production_Data_Cvtg u
							WHERE
							u.RCDIDX				= prd.RcdIdx AND
							u.SITE_DIMENSION_SiteId = ld.SITE_DIMENSION_SiteId  AND
							u.LINE_DIMENSION_CentralLineId	= ld.CentralLineId
							)

Update T SET
	T.[SITE]							= s.[SITE],
	T.[ProcessOrder]					= s.[ProcessOrder],
	T.[PLId]							= s.[PLId],
	T.[PUId]							= s.[PUId],
	T.[EventId]							= s.[EventId],
	T.[StartTime]						= s.[StartTime],
	T.[EndTime]							= s.[EndTime],
	T.[StartTimeUTC]					= s.[StartTimeUTC],
	T.[EndTimeUTC]						= s.[EndTimeUTC],
	T.[ProdId]							= s.[ProdId],
	T.[PLDesc]							= s.[PLDesc],
	T.[ReliabilityPUID]					= s.[ReliabilityPUID],
	T.[PUDesc]							= s.[PUDesc],
	T.[ShiftDesc]						= s.[ShiftDesc],
	T.[TeamDesc]						= s.[TeamDesc],
	T.[ProdCode]						= s.[ProdCode],
	T.[ProdDesc]						= s.[ProdDesc],
	T.[ProdFamily]						= s.[ProdFamily],
	T.[ProdGroup]						= s.[ProdGroup],
	T.[PPId]							= s.[PPId],
	T.[POStatus]						= s.[POStatus],
	T.[PPStatusId]						= s.[PPStatusId],
	T.[BatchNumber]						= s.[BatchNumber],
	T.[TotalUnits]						= s.[TotalUnits],
	T.[GoodUnits]						= s.[GoodUnits],
	T.[RejectUnits]						= s.[RejectUnits],
	T.[WebWidth]						= s.[WebWidth],
	T.[SheetWidth]						= s.[SheetWidth],
	T.[LineSpeedIdeal]					= s.[LineSpeedIdeal],
	T.[LineSpeedTarget]					= s.[LineSpeedTarget],
	T.[LineSpeedAvg]					= s.[LineSpeedAvg],
	T.[TargetLineSpeed]					= s.[TargetLineSpeed],
	T.[LineStatus]						= s.[LineStatus],
	T.[RollsPerLog]						= s.[RollsPerLog],
	T.[RollsInPack]						= s.[RollsInPack],
	T.[PacksInBundle]					= s.[PacksInBundle],
	T.[CartonsInCase]					= s.[CartonsInCase],
	T.[SheetCount]						= s.[SheetCount],
	T.[ShipUnit]						= s.[ShipUnit],
	T.[CalendarRuntime]					= s.[CalendarRuntime],
	T.[ProductionRuntime]				= s.[ProductionRuntime],
	T.[PlanningRuntime]					= s.[PlanningRuntime],
	T.[OperationsRuntime]				= s.[OperationsRuntime],
	T.[SheetLength]						= s.[SheetLength],
	T.[StatFactor]						= s.[StatFactor],
	T.[TargetUnits]						= s.[TargetUnits],
	T.[ActualUnits]						= s.[ActualUnits],
	T.[OperationsTargetUnits]			= s.[OperationsTargetUnits],
	T.[HolidayCurtailDT]				= s.[HolidayCurtailDT],
	T.[PlninterventionDT]				= s.[PlninterventionDT],
	T.[ChangeOverDT]					= s.[ChangeOverDT],
	T.[HygCleaningDT]					= s.[HygCleaningDT],
	T.[EOProjectsDT]					= s.[EOProjectsDT],
	T.[UnscheduledDT]					= s.[UnscheduledDT],
	T.[CLAuditsDT]						= s.[CLAuditsDT],
	T.[IdealUnits]						= s.[IdealUnits],
	T.[RollWidth2Stage]					= s.[RollWidth2Stage],
	T.[RollWidth3Stage]					= s.[RollWidth3Stage],
	T.[SplitUptime]						= s.[SplitUptime],
	T.[Runtime]							= s.[Runtime],
	T.[CnvtLineSpeedToSheetLength]		= s.[CnvtLineSpeedToSheetLength],
	T.[CnvtParentRollWidthToSheetWidth]	= s.[CnvtParentRollWidthToSheetWidth],
	T.[DefaultPMRollWidth]				= s.[DefaultPMRollWidth],
	T.[LineSpeedUOM]					= s.[LineSpeedUOM],
	T.[SheetLengthSpec]					= s.[SheetLengthSpec],
	T.[SheetLengthSpecUOM]				= s.[SheetLengthSpecUOM],
	T.[SheetWidthSpec]					= s.[SheetWidthSpec],
	T.[SheetWidthSpecUOM]				= s.[SheetWidthSpecUOM],
	T.[PlannedRejectLogs]				= s.[PlannedRejectLogs],
	T.[UnplannedRejectLogs]				= s.[UnplannedRejectLogs],
	T.[BreakoutRejectLogs]				= s.[BreakoutRejectLogs],
	T.[ManualRejectLogs]				= s.[ManualRejectLogs],
	T.[OtherRejectLogs]					= s.[OtherRejectLogs],
	T.[ILOCSetpointTarget]				= s.[ILOCSetpointTarget],
	T.[ILOCSetpointAverage]				= s.[ILOCSetpointAverage],
	T.[ILOCSetpointSampleCount]			= s.[ILOCSetpointSampleCount],
	T.[ILOCActualAverage]				= s.[ILOCActualAverage],
	T.[ILOCActualSampleCount]			= s.[ILOCActualSampleCount],
	T.[ts]								= s.[ts],
	T.[deleteflag]						= s.[deleteflag]
from dbo.OpsDB_Production_Data_Cvtg T
JOIN (
				SELECT
					prd.[SITE],
					prd.[ProcessOrder],
					prd.[PLId],
					prd.[PUId],
					prd.[EventId],
					prd.[StartTime],
					prd.[EndTime],
					prd.[StartTimeUTC],
					prd.[EndTimeUTC],
					prd.[ProdId],
					prd.[PLDesc],
					prd.[ReliabilityPUID],
					prd.[PUDesc],
					prd.[ShiftDesc],
					prd.[TeamDesc],
					prd.[ProdCode],
					prd.[ProdDesc],
					prd.[ProdFamily],
					prd.[ProdGroup],
					prd.[PPId],
					prd.[POStatus],
					prd.[PPStatusId],
					prd.[BatchNumber],
					prd.[TotalUnits],
					prd.[GoodUnits],
					prd.[RejectUnits],
					prd.[WebWidth],
					prd.[SheetWidth],
					prd.[LineSpeedIdeal],
					prd.[LineSpeedTarget],
					prd.[LineSpeedAvg],
					prd.[TargetLineSpeed],
					prd.[LineStatus],
					prd.[RollsPerLog],
					prd.[RollsInPack],
					prd.[PacksInBundle],
					prd.[CartonsInCase],
					prd.[SheetCount],
					prd.[ShipUnit],
					prd.[CalendarRuntime],
					prd.[ProductionRuntime],
					prd.[PlanningRuntime],
					prd.[OperationsRuntime],
					prd.[SheetLength],
					prd.[StatFactor],
					prd.[TargetUnits],
					prd.[ActualUnits],
					prd.[OperationsTargetUnits],
					prd.[HolidayCurtailDT],
					prd.[PlninterventionDT],
					prd.[ChangeOverDT],
					prd.[HygCleaningDT],
					prd.[EOProjectsDT],
					prd.[UnscheduledDT],
					prd.[CLAuditsDT],
					prd.[IdealUnits],
					prd.[RollWidth2Stage],
					prd.[RollWidth3Stage],
					prd.[SplitUptime],
					prd.[Runtime],
					prd.[CnvtLineSpeedToSheetLength],
					prd.[CnvtParentRollWidthToSheetWidth],
					prd.[DefaultPMRollWidth],
					prd.[LineSpeedUOM],
					prd.[SheetLengthSpec],
					prd.[SheetLengthSpecUOM],
					prd.[SheetWidthSpec],
					prd.[SheetWidthSpecUOM],
					prd.[PlannedRejectLogs],
					prd.[UnplannedRejectLogs],
					prd.[BreakoutRejectLogs],
					prd.[ManualRejectLogs],
					prd.[OtherRejectLogs],
					prd.[ILOCSetpointTarget],
					prd.[ILOCSetpointAverage],
					prd.[ILOCSetpointSampleCount],
					prd.[ILOCActualAverage],
					prd.[ILOCActualSampleCount],
					prd.[ts],
					prd.[deleteflag],
					prd.[RcdIdx],
					@SiteId AS SITE_DIMENSION_SiteId,
					ld.CentralLineId AS LINE_DIMENSION_CentralLineId
				FROM @ProductionRawdataCvtg prd
				JOIN dbo.LINE_DIMENSION ld ON prd.PLID = ld.PLId AND ld.SITE_DIMENSION_SiteId = @SiteId
) S ON (
			T.SITE_DIMENSION_SiteId			= s.SITE_DIMENSION_SiteId AND
			T.LINE_DIMENSION_CentralLineId	= s.LINE_DIMENSION_CentralLineId AND
			T.RcdIdx						= s.RcdIdx
		)

	UPDATE [dbo].[Transfer_Parameter_Data]
		SET LastModifytime = ( SELECT MAX(TS) FROM @ProductionRawdataCvtg )
	WHERE TableName = 'OpsDB_Production_Data_Cvtg'
	AND SiteId = @SiteId

RETURN
GO

GRANT EXEC ON TYPE::[dbo].[OpsDB_Production_Data_Cvtg_Type]  TO [LocalUser]
GO

GRANT EXECUTE ON OBJECT ::[dbo].splocal_InsertProductionRawDataCvtg  TO [LocalUser]
GO