--DROP PROCEDURE splocal_InsertProductionRawDataPM
--GO

create PROCEDURE splocal_InsertProductionRawDataPM
  @ProductionRawDataPM [dbo].[OpsDB_Production_Data_PM_Type] READONLY
AS
	DECLARE @SiteId INTEGER

	SELECT TOP 1 @SiteId = sd.SiteId
	FROM @ProductionRawDataPM prd
	JOIN SITE_DIMENSION sd ON prd.DataServerName = sd.DataServerName

	INSERT INTO dbo.OpsDB_Production_Data_PM (
		[StartTime],
		[EndTime],
		[StartTimeUTC],
		[EndTimeUTC],
		[Site],
		[PLID],
		[PLDesc],
		[PUID],
		[PUDesc],
		[ProdId],
		[ProdCode],
		[ProdDesc],
		[ProdFam],
		[ProdGroup],
		[ShiftDesc],
		[TeamDesc],
		[NPTStatus],
		[ProcessOrder],
		[ProductTime],
		[GoodTons],
		[RejectTons],
		[HoldTons],
		[FireTons],
		[LastCleaningBlades],
		[LastCrepingBlades],
		[LifeCrepingBlades],
		[LifeCleaningBlades],
		[TAYTons],
		[SlabTons],
		[RepulperTons],
		[TeardownTons],
		[RATons],
		[TotalTons],
		[UnExpTons],
		[GoodRolls],
		[RejectRolls],
		[HoldRolls],
		[FireRolls],
		[CleaningBlades],
		[CrepingBlades],
		[Sheetbreaks],
		[SheetbreaksTime],
		[Stops],
		[YankeeSpeedSum],
		[YankeeSpeedCount],
		[ReelSpeedSum],
		[ReelSpeedCount],
		[FormingWireLife],
		[BackingWireLife],
		[BeltLife],
		[Belt_Id],
		[T3rd_Furnish_Sum],
		[CTMP_Sum],
		[Fiber_1_Sum],
		[Fiber_2_Sum],
		[Long_Fiber_Sum],
		[Machine_Broke_Sum],
		[Product_Broke_Sum],
		[Short_Fiber_Sum],
		[Absorb_Aid_Towel_Sum],
		[Aloe_E_Additive_Sum],
		[Biocide_Sum],
		[Cat_Promoter_Sum],
		[Chem_1_Sum],
		[Chem_2_Sum],
		[Chlorine_Control_Sum],
		[Defoamer_Sum],
		[Dry_Strength_Facial_Sum],
		[Dry_Strength_Tissue_Sum],
		[Recycle_Fiber_Sum],
		[Dry_Strength_Towel_Sum],
		[Dye_1_Sum],
		[Dye_2_Sum],
		[Emulsion_1_Sum],
		[Emulsion_2_Sum],
		[Flocculant_Sum],
		[Glue_Adhesive_Sum],
		[Glue_Crepe_Aid_Sum],
		[Glue_Release_Aid_Sum],
		[Glue_Total_Sum],
		[pH_Control_Tissue_Acid_Sum],
		[pH_Control_Towel_Base_Sum],
		[Single_Glue_Sum],
		[Softener_Facial_Sum],
		[Softener_Tissue_Sum],
		[Softener_Towel_Sum],
		[Wet_Strength_Facial_Sum],
		[Wet_Strength_Tissue_Sum],
		[Wet_Strength_Towel_Sum],
		[Air_Sum],
		[Air_UOM],
		[Air_Per_YKT],
		[Electric_Sum],
		[Electric_UOM],
		[Electric_Per_YKT],
		[Gas_Sum],
		[Gas_UOM],
		[Gas_Per_YKT],
		[Steam_Sum],
		[Steam_UOM],
		[Steam_Per_YKT],
		[Water_Sum],
		[Water_UOM],
		[Water_Per_YKT],
		[GRHF_Tons],
		[All_Tons],
		[All_Furnish],
		[All_Furnish_Perc_Calc],
		[Total_Roll_Status_Cnt],
		[Ts],
		[DeleteFlag],
		[GI_Downtime],
		[GE_Downtime],
		[GI_Uptime],
		[GE_Uptime],
		[RcdIdx],
		[SITE_DIMENSION_SiteId],
		[LINE_DIMENSION_CentralLineId]
	)
	SELECT
		prd.[StartTime],
		prd.[EndTime],
		prd.[StartTimeUTC],
		prd.[EndTimeUTC],
		prd.[Site],
		prd.[PLID],
		prd.[PLDesc],
		prd.[PUID],
		prd.[PUDesc],
		prd.[ProdId],
		prd.[ProdCode],
		prd.[ProdDesc],
		prd.[ProdFam],
		prd.[ProdGroup],
		prd.[ShiftDesc],
		prd.[TeamDesc],
		prd.[NPTStatus],
		prd.[ProcessOrder],
		prd.[ProductTime],
		prd.[GoodTons],
		prd.[RejectTons],
		prd.[HoldTons],
		prd.[FireTons],
		prd.[LastCleaningBlades],
		prd.[LastCrepingBlades],
		prd.[LifeCrepingBlades],
		prd.[LifeCleaningBlades],
		prd.[TAYTons],
		prd.[SlabTons],
		prd.[RepulperTons],
		prd.[TeardownTons],
		prd.[RATons],
		prd.[TotalTons],
		prd.[UnExpTons],
		prd.[GoodRolls],
		prd.[RejectRolls],
		prd.[HoldRolls],
		prd.[FireRolls],
		prd.[CleaningBlades],
		prd.[CrepingBlades],
		prd.[Sheetbreaks],
		prd.[SheetbreaksTime],
		prd.[Stops],
		prd.[YankeeSpeedSum],
		prd.[YankeeSpeedCount],
		prd.[ReelSpeedSum],
		prd.[ReelSpeedCount],
		prd.[FormingWireLife],
		prd.[BackingWireLife],
		prd.[BeltLife],
		prd.[Belt_Id],
		prd.[T3rd_Furnish_Sum],
		prd.[CTMP_Sum],
		prd.[Fiber_1_Sum],
		prd.[Fiber_2_Sum],
		prd.[Long_Fiber_Sum],
		prd.[Machine_Broke_Sum],
		prd.[Product_Broke_Sum],
		prd.[Short_Fiber_Sum],
		prd.[Absorb_Aid_Towel_Sum],
		prd.[Aloe_E_Additive_Sum],
		prd.[Biocide_Sum],
		prd.[Cat_Promoter_Sum],
		prd.[Chem_1_Sum],
		prd.[Chem_2_Sum],
		prd.[Chlorine_Control_Sum],
		prd.[Defoamer_Sum],
		prd.[Dry_Strength_Facial_Sum],
		prd.[Dry_Strength_Tissue_Sum],
		prd.[Recycle_Fiber_Sum],
		prd.[Dry_Strength_Towel_Sum],
		prd.[Dye_1_Sum],
		prd.[Dye_2_Sum],
		prd.[Emulsion_1_Sum],
		prd.[Emulsion_2_Sum],
		prd.[Flocculant_Sum],
		prd.[Glue_Adhesive_Sum],
		prd.[Glue_Crepe_Aid_Sum],
		prd.[Glue_Release_Aid_Sum],
		prd.[Glue_Total_Sum],
		prd.[pH_Control_Tissue_Acid_Sum],
		prd.[pH_Control_Towel_Base_Sum],
		prd.[Single_Glue_Sum],
		prd.[Softener_Facial_Sum],
		prd.[Softener_Tissue_Sum],
		prd.[Softener_Towel_Sum],
		prd.[Wet_Strength_Facial_Sum],
		prd.[Wet_Strength_Tissue_Sum],
		prd.[Wet_Strength_Towel_Sum],
		prd.[Air_Sum],
		prd.[Air_UOM],
		prd.[Air_Per_YKT],
		prd.[Electric_Sum],
		prd.[Electric_UOM],
		prd.[Electric_Per_YKT],
		prd.[Gas_Sum],
		prd.[Gas_UOM],
		prd.[Gas_Per_YKT],
		prd.[Steam_Sum],
		prd.[Steam_UOM],
		prd.[Steam_Per_YKT],
		prd.[Water_Sum],
		prd.[Water_UOM],
		prd.[Water_Per_YKT],
		prd.[GRHF_Tons],
		prd.[All_Tons],
		prd.[All_Furnish],
		prd.[All_Furnish_Perc_Calc],
		prd.[Total_Roll_Status_Cnt],
		prd.[Ts],
		prd.[DeleteFlag],
		prd.[GI_Downtime],
		prd.[GE_Downtime],
		prd.[GI_Uptime],
		prd.[GE_Uptime],
		prd.[RcdIdx],
		@SiteId AS SITE_DIMENSION_SiteId,
		ld.CentralLineId AS LINE_DIMENSION_CentralLineId
		FROM  @ProductionRawDataPM prd
		JOIN dbo.LINE_DIMENSION ld ON prd.PLID = ld.PLId AND ld.SITE_DIMENSION_SiteId = @SiteId
		WHERE NOT EXISTS (  SELECT *
							FROM dbo.OpsDB_Production_Data_PM u
							WHERE
							u.RCDIDX				= prd.RcdIdx AND
							u.SITE_DIMENSION_SiteId = ld.SITE_DIMENSION_SiteId  AND
							u.LINE_DIMENSION_CentralLineId	= ld.CentralLineId
							)

Update T SET
	T.[StartTime]					= s.[StartTime],
	T.[EndTime]						= s.[EndTime],
	T.[StartTimeUTC]				= s.[StartTimeUTC],
	T.[EndTimeUTC]					= s.[EndTimeUTC],
	T.[Site]						= s.[Site],
	T.[PLID]						= s.[PLID],
	T.[PLDesc]						= s.[PLDesc],
	T.[PUID]						= s.[PUID],
	T.[PUDesc]						= s.[PUDesc],
	T.[ProdId]						= s.[ProdId],
	T.[ProdCode]					= s.[ProdCode],
	T.[ProdDesc]					= s.[ProdDesc],
	T.[ProdFam]						= s.[ProdFam],
	T.[ProdGroup]					= s.[ProdGroup],
	T.[ShiftDesc]					= s.[ShiftDesc],
	T.[TeamDesc]					= s.[TeamDesc],
	T.[NPTStatus]					= s.[NPTStatus],
	T.[ProcessOrder]				= s.[ProcessOrder],
	T.[ProductTime]					= s.[ProductTime],
	T.[GoodTons]					= s.[GoodTons],
	T.[RejectTons]					= s.[RejectTons],
	T.[HoldTons]					= s.[HoldTons],
	T.[FireTons]					= s.[FireTons],
	T.[LastCleaningBlades]			= s.[LastCleaningBlades],
	T.[LastCrepingBlades]			= s.[LastCrepingBlades],
	T.[LifeCrepingBlades]			= s.[LifeCrepingBlades],
	T.[LifeCleaningBlades]			= s.[LifeCleaningBlades],
	T.[TAYTons]						= s.[TAYTons],
	T.[SlabTons]					= s.[SlabTons],
	T.[RepulperTons]				= s.[RepulperTons],
	T.[TeardownTons]				= s.[TeardownTons],
	T.[RATons]						= s.[RATons],
	T.[TotalTons]					= s.[TotalTons],
	T.[UnExpTons]					= s.[UnExpTons],
	T.[GoodRolls]					= s.[GoodRolls],
	T.[RejectRolls]					= s.[RejectRolls],
	T.[HoldRolls]					= s.[HoldRolls],
	T.[FireRolls]					= s.[FireRolls],
	T.[CleaningBlades]				= s.[CleaningBlades],
	T.[CrepingBlades]				= s.[CrepingBlades],
	T.[Sheetbreaks]					= s.[Sheetbreaks],
	T.[SheetbreaksTime]				= s.[SheetbreaksTime],
	T.[Stops]						= s.[Stops],
	T.[YankeeSpeedSum]				= s.[YankeeSpeedSum],
	T.[YankeeSpeedCount]			= s.[YankeeSpeedCount],
	T.[ReelSpeedSum]				= s.[ReelSpeedSum],
	T.[ReelSpeedCount]				= s.[ReelSpeedCount],
	T.[FormingWireLife]				= s.[FormingWireLife],
	T.[BackingWireLife]				= s.[BackingWireLife],
	T.[BeltLife]					= s.[BeltLife],
	T.[Belt_Id]						= s.[Belt_Id],
	T.[T3rd_Furnish_Sum]			= s.[T3rd_Furnish_Sum],
	T.[CTMP_Sum]					= s.[CTMP_Sum],
	T.[Fiber_1_Sum]					= s.[Fiber_1_Sum],
	T.[Fiber_2_Sum]					= s.[Fiber_2_Sum],
	T.[Long_Fiber_Sum]				= s.[Long_Fiber_Sum],
	T.[Machine_Broke_Sum]			= s.[Machine_Broke_Sum],
	T.[Product_Broke_Sum]			= s.[Product_Broke_Sum],
	T.[Short_Fiber_Sum]				= s.[Short_Fiber_Sum],
	T.[Absorb_Aid_Towel_Sum]		= s.[Absorb_Aid_Towel_Sum],
	T.[Aloe_E_Additive_Sum]			= s.[Aloe_E_Additive_Sum],
	T.[Biocide_Sum]					= s.[Biocide_Sum],
	T.[Cat_Promoter_Sum]			= s.[Cat_Promoter_Sum],
	T.[Chem_1_Sum]					= s.[Chem_1_Sum],
	T.[Chem_2_Sum]					= s.[Chem_2_Sum],
	T.[Chlorine_Control_Sum]		= s.[Chlorine_Control_Sum],
	T.[Defoamer_Sum]				= s.[Defoamer_Sum],
	T.[Dry_Strength_Facial_Sum]		= s.[Dry_Strength_Facial_Sum],
	T.[Dry_Strength_Tissue_Sum]		= s.[Dry_Strength_Tissue_Sum],
	T.[Recycle_Fiber_Sum]			= s.[Recycle_Fiber_Sum],
	T.[Dry_Strength_Towel_Sum]		= s.[Dry_Strength_Towel_Sum],
	T.[Dye_1_Sum]					= s.[Dye_1_Sum],
	T.[Dye_2_Sum]					= s.[Dye_2_Sum],
	T.[Emulsion_1_Sum]				= s.[Emulsion_1_Sum],
	T.[Emulsion_2_Sum]				= s.[Emulsion_2_Sum],
	T.[Flocculant_Sum]				= s.[Flocculant_Sum],
	T.[Glue_Adhesive_Sum]			= s.[Glue_Adhesive_Sum],
	T.[Glue_Crepe_Aid_Sum]			= s.[Glue_Crepe_Aid_Sum],
	T.[Glue_Release_Aid_Sum]		= s.[Glue_Release_Aid_Sum],
	T.[Glue_Total_Sum]				= s.[Glue_Total_Sum],
	T.[pH_Control_Tissue_Acid_Sum]	= s.[pH_Control_Tissue_Acid_Sum],
	T.[pH_Control_Towel_Base_Sum]	= s.[pH_Control_Towel_Base_Sum],
	T.[Single_Glue_Sum]				= s.[Single_Glue_Sum],
	T.[Softener_Facial_Sum]			= s.[Softener_Facial_Sum],
	T.[Softener_Tissue_Sum]			= s.[Softener_Tissue_Sum],
	T.[Softener_Towel_Sum]			= s.[Softener_Towel_Sum],
	T.[Wet_Strength_Facial_Sum]		= s.[Wet_Strength_Facial_Sum],
	T.[Wet_Strength_Tissue_Sum]		= s.[Wet_Strength_Tissue_Sum],
	T.[Wet_Strength_Towel_Sum]		= s.[Wet_Strength_Towel_Sum],
	T.[Air_Sum]						= s.[Air_Sum],
	T.[Air_UOM]						= s.[Air_UOM],
	T.[Air_Per_YKT]					= s.[Air_Per_YKT],
	T.[Electric_Sum]				= s.[Electric_Sum],
	T.[Electric_UOM]				= s.[Electric_UOM],
	T.[Electric_Per_YKT]			= s.[Electric_Per_YKT],
	T.[Gas_Sum]						= s.[Gas_Sum],
	T.[Gas_UOM]						= s.[Gas_UOM],
	T.[Gas_Per_YKT]					= s.[Gas_Per_YKT],
	T.[Steam_Sum]					= s.[Steam_Sum],
	T.[Steam_UOM]					= s.[Steam_UOM],
	T.[Steam_Per_YKT]				= s.[Steam_Per_YKT],
	T.[Water_Sum]					= s.[Water_Sum],
	T.[Water_UOM]					= s.[Water_UOM],
	T.[Water_Per_YKT]				= s.[Water_Per_YKT],
	T.[GRHF_Tons]					= s.[GRHF_Tons],
	T.[All_Tons]					= s.[All_Tons],
	T.[All_Furnish]					= s.[All_Furnish],
	T.[All_Furnish_Perc_Calc]		= s.[All_Furnish_Perc_Calc],
	T.[Total_Roll_Status_Cnt]		= s.[Total_Roll_Status_Cnt],
	T.[Ts]							= s.[Ts],
	T.[DeleteFlag]					= s.[DeleteFlag],
	T.[GI_Downtime]					= s.[GI_Downtime],
	T.[GE_Downtime]					= s.[GE_Downtime],
	T.[GI_Uptime]					= s.[GI_Uptime],
	T.[GE_Uptime]					= s.[GE_Uptime],
	T.[RcdIdx]						= s.[RcdIdx]
from dbo.OpsDB_Production_Data_PM T
JOIN (
				SELECT
					prd.[StartTime],
					prd.[EndTime],
					prd.[StartTimeUTC],
					prd.[EndTimeUTC],
					prd.[Site],
					prd.[PLID],
					prd.[PLDesc],
					prd.[PUID],
					prd.[PUDesc],
					prd.[ProdId],
					prd.[ProdCode],
					prd.[ProdDesc],
					prd.[ProdFam],
					prd.[ProdGroup],
					prd.[ShiftDesc],
					prd.[TeamDesc],
					prd.[NPTStatus],
					prd.[ProcessOrder],
					prd.[ProductTime],
					prd.[GoodTons],
					prd.[RejectTons],
					prd.[HoldTons],
					prd.[FireTons],
					prd.[LastCleaningBlades],
					prd.[LastCrepingBlades],
					prd.[LifeCrepingBlades],
					prd.[LifeCleaningBlades],
					prd.[TAYTons],
					prd.[SlabTons],
					prd.[RepulperTons],
					prd.[TeardownTons],
					prd.[RATons],
					prd.[TotalTons],
					prd.[UnExpTons],
					prd.[GoodRolls],
					prd.[RejectRolls],
					prd.[HoldRolls],
					prd.[FireRolls],
					prd.[CleaningBlades],
					prd.[CrepingBlades],
					prd.[Sheetbreaks],
					prd.[SheetbreaksTime],
					prd.[Stops],
					prd.[YankeeSpeedSum],
					prd.[YankeeSpeedCount],
					prd.[ReelSpeedSum],
					prd.[ReelSpeedCount],
					prd.[FormingWireLife],
					prd.[BackingWireLife],
					prd.[BeltLife],
					prd.[Belt_Id],
					prd.[T3rd_Furnish_Sum],
					prd.[CTMP_Sum],
					prd.[Fiber_1_Sum],
					prd.[Fiber_2_Sum],
					prd.[Long_Fiber_Sum],
					prd.[Machine_Broke_Sum],
					prd.[Product_Broke_Sum],
					prd.[Short_Fiber_Sum],
					prd.[Absorb_Aid_Towel_Sum],
					prd.[Aloe_E_Additive_Sum],
					prd.[Biocide_Sum],
					prd.[Cat_Promoter_Sum],
					prd.[Chem_1_Sum],
					prd.[Chem_2_Sum],
					prd.[Chlorine_Control_Sum],
					prd.[Defoamer_Sum],
					prd.[Dry_Strength_Facial_Sum],
					prd.[Dry_Strength_Tissue_Sum],
					prd.[Recycle_Fiber_Sum],
					prd.[Dry_Strength_Towel_Sum],
					prd.[Dye_1_Sum],
					prd.[Dye_2_Sum],
					prd.[Emulsion_1_Sum],
					prd.[Emulsion_2_Sum],
					prd.[Flocculant_Sum],
					prd.[Glue_Adhesive_Sum],
					prd.[Glue_Crepe_Aid_Sum],
					prd.[Glue_Release_Aid_Sum],
					prd.[Glue_Total_Sum],
					prd.[pH_Control_Tissue_Acid_Sum],
					prd.[pH_Control_Towel_Base_Sum],
					prd.[Single_Glue_Sum],
					prd.[Softener_Facial_Sum],
					prd.[Softener_Tissue_Sum],
					prd.[Softener_Towel_Sum],
					prd.[Wet_Strength_Facial_Sum],
					prd.[Wet_Strength_Tissue_Sum],
					prd.[Wet_Strength_Towel_Sum],
					prd.[Air_Sum],
					prd.[Air_UOM],
					prd.[Air_Per_YKT],
					prd.[Electric_Sum],
					prd.[Electric_UOM],
					prd.[Electric_Per_YKT],
					prd.[Gas_Sum],
					prd.[Gas_UOM],
					prd.[Gas_Per_YKT],
					prd.[Steam_Sum],
					prd.[Steam_UOM],
					prd.[Steam_Per_YKT],
					prd.[Water_Sum],
					prd.[Water_UOM],
					prd.[Water_Per_YKT],
					prd.[GRHF_Tons],
					prd.[All_Tons],
					prd.[All_Furnish],
					prd.[All_Furnish_Perc_Calc],
					prd.[Total_Roll_Status_Cnt],
					prd.[Ts],
					prd.[DeleteFlag],
					prd.[GI_Downtime],
					prd.[GE_Downtime],
					prd.[GI_Uptime],
					prd.[GE_Uptime],
					prd.[RcdIdx],
					@SiteId AS SITE_DIMENSION_SiteId,
					ld.CentralLineId AS LINE_DIMENSION_CentralLineId
				FROM @ProductionRawDataPM prd
				JOIN dbo.LINE_DIMENSION ld ON prd.PLID = ld.PLId AND ld.SITE_DIMENSION_SiteId = @SiteId
) S ON (
			T.SITE_DIMENSION_SiteId			= s.SITE_DIMENSION_SiteId AND
			T.LINE_DIMENSION_CentralLineId	= s.LINE_DIMENSION_CentralLineId AND
			T.RcdIdx						= s.RcdIdx
		)

	UPDATE [dbo].[Transfer_Parameter_Data]
		SET LastModifytime = ( SELECT MAX(TS) FROM @ProductionRawDataPM )
	WHERE TableName = 'OpsDB_Production_Data_PM'
	AND SiteId = @SiteId

RETURN
GO

GRANT EXEC ON TYPE::[dbo].[OpsDB_Production_Data_PM_Type]  TO [LocalUser]
GO

GRANT EXECUTE ON OBJECT ::[dbo].splocal_InsertProductionRawDataPM  TO [LocalUser]
GO
