--DROP PROCEDURE splocal_InsertELPRawData;
--GO

CREATE PROCEDURE splocal_InsertELPRawData
   @ELPRawdata [dbo].[OpsDB_ELP_Data_Type] READONLY
AS
	DECLARE @SiteId INTEGER

	SELECT TOP 1 @SiteId = sd.SiteId 
	FROM @ELPRawdata e
	JOIN SITE_DIMENSION sd ON e.DataServerName = sd.DataServerName
	
	INSERT INTO [dbo].[OpsDB_ELP_Data] (
	[Site]								,
	[PRConvStartTime]					,
	[PRConvEndTime]						,
	[PRConvStartTimeUTC]				,
	[PRConvEndTimeUTC]					,
	[PLId]								,
	[PLDesc]							,
	[PUId]								,
	[PUDesc]							,
	[NPTStatus]							,
	[ProcessOrder]						,
	[ProdId]							,
	[ProdCode]							,
	[ProdDesc]							,
	[ProdFam]							,
	[ProdGroup]							,
	[ParentType]						,
	[ParentPRID]						,
	[ParentPM]							,
	[ParentTeam]						,
	[ParentPLId]						,
	[ParentPLDesc]						,
	[ParentPUId]						,
	[ParentPUDesc]						,
	[GrandParentPRID]					,
	[GrandParentPM]						,
	[GrandParentTeam]					,
	[PM]								,
	[PMTeam]							,
	[PaperSource]						,
	[PaperRunBy]						,
	[INTR]								,
	[EventId]							,
	[SourceId]							,
	[EventNum]							,
	[EventTimestamp]					,
	[UWS]								,
	[InputOrder]						,
	[ParentRollTimestamp]				,
	[ParentRollAge]						,
	[TotalRuntime]						,
	[TotalRolls]						,
	[FreshRolls]						,
	[StorageRolls]						,
	[TotalStops]						,
	[TotalDowntime]						,
	[TotalRateLossDT]					,
	[TotalScheduledDT]					,
	[PaperRuntime]						,
	[StartTimeLine]						,
	[EndTimeLine]						,
	[TotalRuntimeLine]					,
	[TotalStopsLine]					,
	[TotalDowntimeLine]					,
	[TotalRateLossDTLine]				,
	[TotalScheduledDTLine]				,
	[TotalFreshRuntimeLine]				,
	[TotalFreshStopsLine]				,
	[TotalFreshDowntimeLine]			,
	[TotalFreshRateLossDTLine]			,
	[TotalFreshScheduledDTLine]			,
	[TotalStorageRuntimeLine]			,
	[TotalStorageStopsLine]				,
	[TotalStorageDowntimeLine]			,
	[TotalStorageRateLossDTLine]		,
	[TotalStorageScheduledDTLine]		,
	[StartTimeLinePS]					,
	[EndTimeLinePS]						,
	[TotalRuntimeLinePS]				,
	[TotalStopsLinePS]					,
	[TotalDowntimeLinePS]				,
	[TotalRateLossDTLinePS]				,
	[TotalScheduledDTLinePS]			,
	[TotalFreshRuntimeLinePS]			,
	[TotalFreshStopsLinePS]				,
	[TotalFreshDowntimeLinePS]			,
	[TotalFreshRateLossDTLinePS]		,
	[TotalFreshScheduledDTLinePS]		,
	[TotalStorageRuntimeLinePS]			,
	[TotalStorageStopsLinePS]			,
	[TotalStorageDowntimeLinePS]		,
	[TotalStorageRateLossDTLinePS]		,
	[TotalStorageScheduledDTLinePS]		,
	[StartTimeIntrPL]					,
	[EndTimeIntrPL]						,
	[TotalRuntimeIntrPL]				,
	[TotalStopsIntrPL]					,
	[TotalDowntimeIntrPL]				,
	[TotalRateLossDTIntrPL]				,
	[TotalScheduledDTIntrPL]			,
	[TotalFreshRuntimeIntrPL]			,
	[TotalFreshStopsIntrPL]				,
	[TotalFreshDowntimeIntrPL]			,
	[TotalFreshRateLossDTIntrPL]		,
	[TotalFreshScheduledDTIntrPL]		,
	[TotalStorageRuntimeIntrPL]			,
	[TotalStorageStopsIntrPL]			,
	[TotalStorageDowntimeIntrPL]		,
	[TotalStorageRateLossDTIntrPL]		,
	[TotalStorageScheduledDTIntrPL]		,
	[StartTimePMRunBy]					,
	[EndTimePMRunBy]					,
	[TotalRuntimePMRunBy]				,
	[TotalStopsPMRunBy] 				,
	[TotalDowntimePMRunBy]				,
	[TotalRateLossDTPMRunBy]			,
	[TotalScheduledDTPMRunBy]			,
	[TotalFreshRuntimePMRunBy]			,
	[TotalFreshStopsPMRunBy]			,
	[TotalFreshDowntimePMRunBy]			,
	[TotalFreshRateLossDTPMRunBy]		,
	[TotalFreshScheduledDTPMRunBy]		,
	[TotalStorageRuntimePMRunBy]		,
	[TotalStorageStopsPMRunBy]			,
	[TotalStorageDowntimePMRunBy]		,
	[TotalStorageRateLossDTPMRunBy]		,
	[TotalStorageScheduledDTPMRunBy]	,
	[TS]								,
	[DeleteFlag]						,
	[SITE_DIMENSION_SiteId]				,
	[LINE_DIMENSION_CentralLineId]		,
	[RcdIdx]
	)	
	SELECT
	elp.[Site]								,
	elp.[PRConvStartTime]					,
	elp.[PRConvEndTime]						,
	elp.[PRConvStartTimeUTC]				,
	elp.[PRConvEndTimeUTC]					,
	elp.[PLId]								,
	elp.[PLDesc]							,
	elp.[PUId]								,
	elp.[PUDesc]							,
	elp.[NPTStatus]							,
	elp.[ProcessOrder]						,
	elp.[ProdId]							,
	elp.[ProdCode]							,
	elp.[ProdDesc]							,
	elp.[ProdFam]							,
	elp.[ProdGroup]							,
	elp.[ParentType]						,
	elp.[ParentPRID]						,
	elp.[ParentPM]							,
	elp.[ParentTeam]						,
	elp.[ParentPLId]						,
	elp.[ParentPLDesc]						,
	elp.[ParentPUId]						,
	elp.[ParentPUDesc]						,
	elp.[GrandParentPRID]					,
	elp.[GrandParentPM]						,
	elp.[GrandParentTeam]					,
	elp.[PM]								,
	elp.[PMTeam]							,
	elp.[PaperSource]						,
	elp.[PaperRunBy]						,
	elp.[INTR]								,
	elp.[EventId]							,
	elp.[SourceId]							,
	elp.[EventNum]							,
	elp.[EventTimestamp] [datetime]			,
	elp.[UWS]								,
	elp.[InputOrder]						,
	elp.[ParentRollTimestamp]				,
	elp.[ParentRollAge]						,
	elp.[TotalRuntime]						,
	elp.[TotalRolls]						,
	elp.[FreshRolls]						,
	elp.[StorageRolls]						,
	elp.[TotalStops]						,
	elp.[TotalDowntime]						,
	elp.[TotalRateLossDT]					,
	elp.[TotalScheduledDT]					,
	elp.[PaperRuntime]						,
	elp.[StartTimeLine]						,
	elp.[EndTimeLine]						,
	elp.[TotalRuntimeLine]					,
	elp.[TotalStopsLine]					,
	elp.[TotalDowntimeLine]					,
	elp.[TotalRateLossDTLine]				,
	elp.[TotalScheduledDTLine]				,
	elp.[TotalFreshRuntimeLine]				,
	elp.[TotalFreshStopsLine]				,
	elp.[TotalFreshDowntimeLine]			,
	elp.[TotalFreshRateLossDTLine]			,
	elp.[TotalFreshScheduledDTLine]			,
	elp.[TotalStorageRuntimeLine]			,
	elp.[TotalStorageStopsLine]				,
	elp.[TotalStorageDowntimeLine]			,
	elp.[TotalStorageRateLossDTLine]		,
	elp.[TotalStorageScheduledDTLine]		,
	elp.[StartTimeLinePS]					,
	elp.[EndTimeLinePS]						,
	elp.[TotalRuntimeLinePS]				,
	elp.[TotalStopsLinePS]					,
	elp.[TotalDowntimeLinePS]				,
	elp.[TotalRateLossDTLinePS]				,
	elp.[TotalScheduledDTLinePS]			,
	elp.[TotalFreshRuntimeLinePS]			,
	elp.[TotalFreshStopsLinePS]				,
	elp.[TotalFreshDowntimeLinePS]			,
	elp.[TotalFreshRateLossDTLinePS]		,
	elp.[TotalFreshScheduledDTLinePS]		,
	elp.[TotalStorageRuntimeLinePS]			,
	elp.[TotalStorageStopsLinePS]			,
	elp.[TotalStorageDowntimeLinePS]		,
	elp.[TotalStorageRateLossDTLinePS]		,
	elp.[TotalStorageScheduledDTLinePS]		,
	elp.[StartTimeIntrPL]					,
	elp.[EndTimeIntrPL]						,
	elp.[TotalRuntimeIntrPL]				,
	elp.[TotalStopsIntrPL]					,
	elp.[TotalDowntimeIntrPL]				,
	elp.[TotalRateLossDTIntrPL]				,
	elp.[TotalScheduledDTIntrPL]			,
	elp.[TotalFreshRuntimeIntrPL]			,
	elp.[TotalFreshStopsIntrPL]				,
	elp.[TotalFreshDowntimeIntrPL]			,
	elp.[TotalFreshRateLossDTIntrPL]		,
	elp.[TotalFreshScheduledDTIntrPL]		,
	elp.[TotalStorageRuntimeIntrPL]			,
	elp.[TotalStorageStopsIntrPL]			,
	elp.[TotalStorageDowntimeIntrPL]		,
	elp.[TotalStorageRateLossDTIntrPL]		,
	elp.[TotalStorageScheduledDTIntrPL]		,
	elp.[StartTimePMRunBy]					,
	elp.[EndTimePMRunBy]					,
	elp.[TotalRuntimePMRunBy]				,
	elp.[TotalStopsPMRunBy] 				,
	elp.[TotalDowntimePMRunBy]				,
	elp.[TotalRateLossDTPMRunBy]			,
	elp.[TotalScheduledDTPMRunBy]			,
	elp.[TotalFreshRuntimePMRunBy]			,
	elp.[TotalFreshStopsPMRunBy]			,
	elp.[TotalFreshDowntimePMRunBy]			,
	elp.[TotalFreshRateLossDTPMRunBy]		,
	elp.[TotalFreshScheduledDTPMRunBy]		,
	elp.[TotalStorageRuntimePMRunBy]		,
	elp.[TotalStorageStopsPMRunBy]			,
	elp.[TotalStorageDowntimePMRunBy]		,
	elp.[TotalStorageRateLossDTPMRunBy]		,
	elp.[TotalStorageScheduledDTPMRunBy]	,
	elp.[TS]								,
	elp.[DeleteFlag]						,
	@SiteId AS SITE_DIMENSION_SiteId		,
	ld.CentralLineId AS LINE_DIMENSION_CentralLineId ,
	elp.[RcdIdx] 
	FROM  @ELPRawdata elp
	JOIN dbo.LINE_DIMENSION ld ON elp.PLID = ld.PLId AND ld.SITE_DIMENSION_SiteId = @SiteId
	WHERE NOT EXISTS (  SELECT * 
							FROM [dbo].[OpsDB_ELP_Data] u 
							WHERE
							u.RCDIDX						= elp.RcdIdx AND 
							u.SITE_DIMENSION_SiteId			= ld.SITE_DIMENSION_SiteId  AND
							u.LINE_DIMENSION_CentralLineId	= ld.CentralLineId
							) 




Update T SET
				T.[Site]							   =				S.[Site]													,
				T.[PRConvStartTime]					   =				S.[PRConvStartTime]											,
				T.[PRConvEndTime]					   =				S.[PRConvEndTime]											,
				T.[PRConvStartTimeUTC]				   =				S.[PRConvStartTimeUTC]										,
				T.[PRConvEndTimeUTC]				   =				S.[PRConvEndTimeUTC]										,
				T.[PLId]							   =				S.[PLId]													,
				T.[PLDesc]							   =				S.[PLDesc]													,
				T.[PUId]							   =				S.[PUId]													,
				T.[PUDesc]							   =				S.[PUDesc]													,
				T.[NPTStatus]						   =				S.[NPTStatus]												,
				T.[ProcessOrder]					   =				S.[ProcessOrder]											,
				T.[ProdId]							   =				S.[ProdId]													,
				T.[ProdCode]						   =				S.[ProdCode]												,
				T.[ProdDesc]						   =				S.[ProdDesc]												,
				T.[ProdFam]							   =				S.[ProdFam]													,
				T.[ProdGroup]						   =				S.[ProdGroup]												,
				T.[ParentType]						   =				S.[ParentType]												,
				T.[ParentPRID]						   =				S.[ParentPRID]												,
				T.[ParentPM]						   =				S.[ParentPM]												,
				T.[ParentTeam]						   =				S.[ParentTeam]												,
				T.[ParentPLId]						   =				S.[ParentPLId]												,
				T.[ParentPLDesc]					   =				S.[ParentPLDesc]											,
				T.[ParentPUId]						   =				S.[ParentPUId]												,
				T.[ParentPUDesc]					   =				S.[ParentPUDesc]											,
				T.[GrandParentPRID]					   =				S.[GrandParentPRID]											,
				T.[GrandParentPM]					   =				S.[GrandParentPM]											,
				T.[GrandParentTeam]					   =				S.[GrandParentTeam]											,
				T.[PM]								   =				S.[PM]														,
				T.[PMTeam]							   =				S.[PMTeam]													,
				T.[PaperSource]						   =				S.[PaperSource]												,
				T.[PaperRunBy]						   =				S.[PaperRunBy]												,
				T.[INTR]							   =				S.[INTR]													,
				T.[EventId]							   =				S.[EventId]													,
				T.[SourceId]						   =				S.[SourceId]												,
				T.[EventNum]						   =				S.[EventNum]												,
				T.[EventTimestamp]					   =				S.[EventTimestamp]											,
				T.[UWS]								   =				S.[UWS]														,
				T.[InputOrder]						   =				S.[InputOrder]												,
				T.[ParentRollTimestamp]				   =				S.[ParentRollTimestamp]										,
				T.[ParentRollAge]					   =				S.[ParentRollAge]											,
				T.[TotalRuntime]					   =				S.[TotalRuntime]											,
				T.[TotalRolls]						   =				S.[TotalRolls]												,
				T.[FreshRolls]						   =				S.[FreshRolls]												,
				T.[StorageRolls]					   =				S.[StorageRolls]											,
				T.[TotalStops]						   =				S.[TotalStops]												,
				T.[TotalDowntime]					   =				S.[TotalDowntime]											,
				T.[TotalRateLossDT]					   =				S.[TotalRateLossDT]											,
				T.[TotalScheduledDT]				   =				S.[TotalScheduledDT]										,
				T.[PaperRuntime]					   =				S.[PaperRuntime]											,
				T.[StartTimeLine]					   =				S.[StartTimeLine]											,
				T.[EndTimeLine]						   =				S.[EndTimeLine]												,
				T.[TotalRuntimeLine]				   =				S.[TotalRuntimeLine]										,
				T.[TotalStopsLine]					   =				S.[TotalStopsLine]											,
				T.[TotalDowntimeLine]				   =				S.[TotalDowntimeLine]										,
				T.[TotalRateLossDTLine]				   =				S.[TotalRateLossDTLine]										,
				T.[TotalScheduledDTLine]			   =				S.[TotalScheduledDTLine]									,
				T.[TotalFreshRuntimeLine]			   =				S.[TotalFreshRuntimeLine]									,
				T.[TotalFreshStopsLine]				   =				S.[TotalFreshStopsLine]										,
				T.[TotalFreshDowntimeLine]			   =				S.[TotalFreshDowntimeLine]									,
				T.[TotalFreshRateLossDTLine]		   =				S.[TotalFreshRateLossDTLine]								,
				T.[TotalFreshScheduledDTLine]		   =				S.[TotalFreshScheduledDTLine]								,
				T.[TotalStorageRuntimeLine]			   =				S.[TotalStorageRuntimeLine]									,
				T.[TotalStorageStopsLine]			   =				S.[TotalStorageStopsLine]									,
				T.[TotalStorageDowntimeLine]		   =				S.[TotalStorageDowntimeLine]								,
				T.[TotalStorageRateLossDTLine]		   =				S.[TotalStorageRateLossDTLine]								,
				T.[TotalStorageScheduledDTLine]		   =				S.[TotalStorageScheduledDTLine]								,
				T.[StartTimeLinePS]					   =				S.[StartTimeLinePS]											,
				T.[EndTimeLinePS]					   =				S.[EndTimeLinePS]											,
				T.[TotalRuntimeLinePS]				   =				S.[TotalRuntimeLinePS]										,
				T.[TotalStopsLinePS]				   =				S.[TotalStopsLinePS]										,
				T.[TotalDowntimeLinePS]				   =				S.[TotalDowntimeLinePS]										,
				T.[TotalRateLossDTLinePS]			   =				S.[TotalRateLossDTLinePS]									,
				T.[TotalScheduledDTLinePS]			   =				S.[TotalScheduledDTLinePS]									,
				T.[TotalFreshRuntimeLinePS]			   =				S.[TotalFreshRuntimeLinePS]									,
				T.[TotalFreshStopsLinePS]			   =				S.[TotalFreshStopsLinePS]									,
				T.[TotalFreshDowntimeLinePS]		   =				S.[TotalFreshDowntimeLinePS]								,
				T.[TotalFreshRateLossDTLinePS]		   =				S.[TotalFreshRateLossDTLinePS]								,
				T.[TotalFreshScheduledDTLinePS]		   =				S.[TotalFreshScheduledDTLinePS]								,
				T.[TotalStorageRuntimeLinePS]		   =				S.[TotalStorageRuntimeLinePS]								,
				T.[TotalStorageStopsLinePS]			   =				S.[TotalStorageStopsLinePS]									,
				T.[TotalStorageDowntimeLinePS]		   =				S.[TotalStorageDowntimeLinePS]								,
				T.[TotalStorageRateLossDTLinePS]	   =				S.[TotalStorageRateLossDTLinePS]							,
				T.[TotalStorageScheduledDTLinePS]	   =				S.[TotalStorageScheduledDTLinePS]							,
				T.[StartTimeIntrPL]					   =				S.[StartTimeIntrPL]											,
				T.[EndTimeIntrPL]					   =				S.[EndTimeIntrPL]											,
				T.[TotalRuntimeIntrPL]				   =				S.[TotalRuntimeIntrPL]										,
				T.[TotalStopsIntrPL]				   =				S.[TotalStopsIntrPL]										,
				T.[TotalDowntimeIntrPL]				   =				S.[TotalDowntimeIntrPL]										,
				T.[TotalRateLossDTIntrPL]			   =				S.[TotalRateLossDTIntrPL]									,
				T.[TotalScheduledDTIntrPL]			   =				S.[TotalScheduledDTIntrPL]									,
				T.[TotalFreshRuntimeIntrPL]			   =				S.[TotalFreshRuntimeIntrPL]									,
				T.[TotalFreshStopsIntrPL]			   =				S.[TotalFreshStopsIntrPL]									,
				T.[TotalFreshDowntimeIntrPL]		   =				S.[TotalFreshDowntimeIntrPL]								,
				T.[TotalFreshRateLossDTIntrPL]		   =				S.[TotalFreshRateLossDTIntrPL]								,
				T.[TotalFreshScheduledDTIntrPL]		   =				S.[TotalFreshScheduledDTIntrPL]								,
				T.[TotalStorageRuntimeIntrPL]		   =				S.[TotalStorageRuntimeIntrPL]								,
				T.[TotalStorageStopsIntrPL]			   =				S.[TotalStorageStopsIntrPL]									,
				T.[TotalStorageDowntimeIntrPL]		   =				S.[TotalStorageDowntimeIntrPL]								,
				T.[TotalStorageRateLossDTIntrPL]	   =				S.[TotalStorageRateLossDTIntrPL]							,
				T.[TotalStorageScheduledDTIntrPL]	   =				S.[TotalStorageScheduledDTIntrPL]							,
				T.[StartTimePMRunBy]				   =				S.[StartTimePMRunBy]										,
				T.[EndTimePMRunBy]					   =				S.[EndTimePMRunBy]											,
				T.[TotalRuntimePMRunBy]				   =				S.[TotalRuntimePMRunBy]										,
				T.[TotalStopsPMRunBy]				   =				S.[TotalStopsPMRunBy]										,
				T.[TotalDowntimePMRunBy]			   =				S.[TotalDowntimePMRunBy]									,
				T.[TotalRateLossDTPMRunBy]			   =				S.[TotalRateLossDTPMRunBy]									,
				T.[TotalScheduledDTPMRunBy]			   =				S.[TotalScheduledDTPMRunBy]									,
				T.[TotalFreshRuntimePMRunBy]		   =				S.[TotalFreshRuntimePMRunBy]								,
				T.[TotalFreshStopsPMRunBy]			   =				S.[TotalFreshStopsPMRunBy]									,
				T.[TotalFreshDowntimePMRunBy]		   =				S.[TotalFreshDowntimePMRunBy]								,
				T.[TotalFreshRateLossDTPMRunBy]		   =				S.[TotalFreshRateLossDTPMRunBy]								,
				T.[TotalFreshScheduledDTPMRunBy]	   =				S.[TotalFreshScheduledDTPMRunBy]							,
				T.[TotalStorageRuntimePMRunBy]		   =				S.[TotalStorageRuntimePMRunBy]								,
				T.[TotalStorageStopsPMRunBy]		   =				S.[TotalStorageStopsPMRunBy]								,
				T.[TotalStorageDowntimePMRunBy]		   =				S.[TotalStorageDowntimePMRunBy]								,
				T.[TotalStorageRateLossDTPMRunBy]	   =				S.[TotalStorageRateLossDTPMRunBy]							,
				T.[TotalStorageScheduledDTPMRunBy]	   =				S.[TotalStorageScheduledDTPMRunBy]							,
				T.[TS]								   =				S.[TS]														,
				T.[DeleteFlag]						   =				S.[DeleteFlag]						

from [dbo].[OpsDB_ELP_Data] T
JOIN (
               SELECT                              
				[Site]								,
				[PRConvStartTime]					,
				[PRConvEndTime]						,
				[PRConvStartTimeUTC]				,
				[PRConvEndTimeUTC]					,
				d.[PLId]							,
				[PLDesc]							,
				[PUId]								,
				[PUDesc]							,
				[NPTStatus]							,
				[ProcessOrder]						,
				[ProdId]							,
				[ProdCode]							,
				[ProdDesc]							,
				[ProdFam]							,
				[ProdGroup]							,
				[ParentType]						,
				[ParentPRID]						,
				[ParentPM]							,
				[ParentTeam]						,
				[ParentPLId]						,
				[ParentPLDesc]						,
				[ParentPUId]						,
				[ParentPUDesc]						,
				[GrandParentPRID]					,
				[GrandParentPM]						,
				[GrandParentTeam]					,
				[PM]								,
				[PMTeam]							,
				[PaperSource]						,
				[PaperRunBy]						,
				[INTR]								,
				[EventId]							,
				[SourceId]							,
				[EventNum]							,
				[EventTimestamp]					,
				[UWS]								,
				[InputOrder]						,
				[ParentRollTimestamp]				,
				[ParentRollAge]						,
				[TotalRuntime]						,
				[TotalRolls]						,
				[FreshRolls]						,
				[StorageRolls]						,
				[TotalStops]						,
				[TotalDowntime]						,
				[TotalRateLossDT]					,
				[TotalScheduledDT]					,
				[PaperRuntime]						,
				[StartTimeLine]						,
				[EndTimeLine]						,
				[TotalRuntimeLine]					,
				[TotalStopsLine]					,
				[TotalDowntimeLine]					,
				[TotalRateLossDTLine]				,
				[TotalScheduledDTLine]				,
				[TotalFreshRuntimeLine]				,
				[TotalFreshStopsLine]				,
				[TotalFreshDowntimeLine]			,
				[TotalFreshRateLossDTLine]			,
				[TotalFreshScheduledDTLine]			,
				[TotalStorageRuntimeLine]			,
				[TotalStorageStopsLine]				,
				[TotalStorageDowntimeLine]			,
				[TotalStorageRateLossDTLine]		,
				[TotalStorageScheduledDTLine]		,
				[StartTimeLinePS] 					,
				[EndTimeLinePS]						,
				[TotalRuntimeLinePS]				,
				[TotalStopsLinePS]					,
				[TotalDowntimeLinePS]				,
				[TotalRateLossDTLinePS]				,
				[TotalScheduledDTLinePS]			,
				[TotalFreshRuntimeLinePS]			,
				[TotalFreshStopsLinePS]				,
				[TotalFreshDowntimeLinePS]			,
				[TotalFreshRateLossDTLinePS]		,
				[TotalFreshScheduledDTLinePS]		,
				[TotalStorageRuntimeLinePS]			,
				[TotalStorageStopsLinePS]			,
				[TotalStorageDowntimeLinePS]		,
				[TotalStorageRateLossDTLinePS]		,
				[TotalStorageScheduledDTLinePS]		,
				[StartTimeIntrPL]					,
				[EndTimeIntrPL]						,
				[TotalRuntimeIntrPL]				,
				[TotalStopsIntrPL]					,
				[TotalDowntimeIntrPL]				,
				[TotalRateLossDTIntrPL]				,
				[TotalScheduledDTIntrPL]			,
				[TotalFreshRuntimeIntrPL]			,
				[TotalFreshStopsIntrPL]				,
				[TotalFreshDowntimeIntrPL]			,
				[TotalFreshRateLossDTIntrPL]		,
				[TotalFreshScheduledDTIntrPL]		,
				[TotalStorageRuntimeIntrPL]			,
				[TotalStorageStopsIntrPL]			,
				[TotalStorageDowntimeIntrPL]		,
				[TotalStorageRateLossDTIntrPL]		,
				[TotalStorageScheduledDTIntrPL]		,
				[StartTimePMRunBy]					,
				[EndTimePMRunBy]					,
				[TotalRuntimePMRunBy]				,
				[TotalStopsPMRunBy] 				,
				[TotalDowntimePMRunBy]				,
				[TotalRateLossDTPMRunBy]			,
				[TotalScheduledDTPMRunBy]			,
				[TotalFreshRuntimePMRunBy]			,
				[TotalFreshStopsPMRunBy]			,
				[TotalFreshDowntimePMRunBy]			,
				[TotalFreshRateLossDTPMRunBy]		,
				[TotalFreshScheduledDTPMRunBy]		,
				[TotalStorageRuntimePMRunBy]		,
				[TotalStorageStopsPMRunBy]			,
				[TotalStorageDowntimePMRunBy]		,
				[TotalStorageRateLossDTPMRunBy]		,
				[TotalStorageScheduledDTPMRunBy]	,
				[TS]								,
				[DeleteFlag]						,
				ld.SITE_DIMENSION_SiteId			,
				ld.CentralLineId					,
				RcdIdx	
                FROM @ELPRawdata d 
				JOIN dbo.LINE_DIMENSION ld ON d.PLID = ld.PLId AND ld.SITE_DIMENSION_SiteId = @SiteId
) S ON (
						T.[SITE_DIMENSION_SiteId]		= s.SITE_DIMENSION_SiteId AND
						T.LINE_DIMENSION_CentralLineId	= s.CentralLineid AND
						T.RcdIdx						= s.RcdIdx	
	    )

	UPDATE [dbo].[Transfer_Parameter_Data]
		SET LastModifytime = ( SELECT MAX(TS) FROM @ELPRawdata )
	WHERE TableName = 'OpsDB_ELP_Data'
	AND SiteId = @SiteId

RETURN
;
GO

GRANT EXEC ON TYPE::[dbo].[OpsDB_ELP_Data_Type]  TO [LocalUser]
GO

GRANT EXECUTE ON OBJECT ::[dbo].splocal_InsertELPRawData  TO [LocalUser]
GO