DROP PROCEDURE splocal_InsertProductionRawDataCvtg;
GO

CREATE PROCEDURE splocal_InsertProductionRawDataCvtg
  @ProductionRawdataCvtg [dbo].[OpsDB_Production_Data_Cvtg_Type] READONLY
AS
	DECLARE @SiteId INTEGER

	SELECT TOP 1 @SiteId = sd.SiteId 
	FROM @ProductionRawdataCvtg dtd
	JOIN SITE_DIMENSION sd ON dtd.DataServerName = sd.DataServerName
	
	INSERT INTO dbo.OpsDB_Production_Data_Cvtg (
		[SITE],
		[ProcessOrder],
		[PLId],
		[PUId],
		[EventId],
		[StartTime],
		[EndTime],
		[StartTimeUTC],
		[EndTimeUTC],
		[ProdId],
		[PLDesc],
		[ReliabilityPUID],
		[PUDesc],
		[ShiftDesc],
		[TeamDesc],
		[ProdCode],
		[ProdDesc],
		[ProdFamily],
		[ProdGroup],
		[PPId],
		[POStatus],
		[PPStatusId],
		[BatchNumber],
		[TotalUnits],
		[GoodUnits],
		[RejectUnits],
		[WebWidth],
		[SheetWidth],
		[LineSpeedIdeal],
		[LineSpeedTarget],
		[LineSpeedAvg],
		[TargetLineSpeed],
		[LineStatus],
		[RollsPerLog],
		[RollsInPack],
		[PacksInBundle],
		[CartonsInCase],
		[SheetCount],
		[ShipUnit],
		[CalendarRuntime],
		[ProductionRuntime],
		[PlanningRuntime],
		[OperationsRuntime],
		[SheetLength],
		[StatFactor],
		[TargetUnits],
		[ActualUnits],
		[OperationsTargetUnits],
		[HolidayCurtailDT],
		[PlninterventionDT],
		[ChangeOverDT],
		[HygCleaningDT],
		[EOProjectsDT],
		[UnscheduledDT],
		[CLAuditsDT],
		[IdealUnits],
		[RollWidth2Stage],
		[RollWidth3Stage],
		[SplitUptime],
		[Runtime],
		[CnvtLineSpeedToSheetLength],
		[CnvtParentRollWidthToSheetWidth],
		[DefaultPMRollWidth],
		[LineSpeedUOM],
		[SheetLengthSpec],
		[SheetLengthSpecUOM],
		[SheetWidthSpec],
		[SheetWidthSpecUOM],
		[PlannedRejectLogs],
		[UnplannedRejectLogs],
		[BreakoutRejectLogs],
		[ManualRejectLogs],
		[OtherRejectLogs],
		[ILOCSetpointTarget],
		[ILOCSetpointAverage],
		[ILOCSetpointSampleCount],
		[ILOCActualAverage],
		[ILOCActualSampleCount],
		[ts],
		[deleteflag],
		[RcdIdx],
		[SITE_DIMENSION_SiteId],
		[LINE_DIMENSION_CentralLineId]
	)	
	SELECT
		prd.[SITE],
		prd.[ProcessOrder],
		prd.[PLId],
		prd.[PUId],
		prd.[EventId],
		prd.[StartTime],
		prd.[EndTime],
		prd.[StartTimeUTC],
		prd.[EndTimeUTC],
		prd.[ProdId],
		prd.[PLDesc],
		prd.[ReliabilityPUID],
		prd.[PUDesc],
		prd.[ShiftDesc],
		prd.[TeamDesc],
		prd.[ProdCode],
		prd.[ProdDesc],
		prd.[ProdFamily],
		prd.[ProdGroup],
		prd.[PPId],
		prd.[POStatus],
		prd.[PPStatusId],
		prd.[BatchNumber],
		prd.[TotalUnits],
		prd.[GoodUnits],
		prd.[RejectUnits],
		prd.[WebWidth],
		prd.[SheetWidth],
		prd.[LineSpeedIdeal],
		prd.[LineSpeedTarget],
		prd.[LineSpeedAvg],
		prd.[TargetLineSpeed],
		prd.[LineStatus],
		prd.[RollsPerLog],
		prd.[RollsInPack],
		prd.[PacksInBundle],
		prd.[CartonsInCase],
		prd.[SheetCount],
		prd.[ShipUnit],
		prd.[CalendarRuntime],
		prd.[ProductionRuntime],
		prd.[PlanningRuntime],
		prd.[OperationsRuntime],
		prd.[SheetLength],
		prd.[StatFactor],
		prd.[TargetUnits],
		prd.[ActualUnits],
		prd.[OperationsTargetUnits],
		prd.[HolidayCurtailDT],
		prd.[PlninterventionDT],
		prd.[ChangeOverDT],
		prd.[HygCleaningDT],
		prd.[EOProjectsDT],
		prd.[UnscheduledDT],
		prd.[CLAuditsDT],
		prd.[IdealUnits],
		prd.[RollWidth2Stage],
		prd.[RollWidth3Stage],
		prd.[SplitUptime],
		prd.[Runtime],
		prd.[CnvtLineSpeedToSheetLength],
		prd.[CnvtParentRollWidthToSheetWidth],
		prd.[DefaultPMRollWidth],
		prd.[LineSpeedUOM],
		prd.[SheetLengthSpec],
		prd.[SheetLengthSpecUOM],
		prd.[SheetWidthSpec],
		prd.[SheetWidthSpecUOM],
		prd.[PlannedRejectLogs],
		prd.[UnplannedRejectLogs],
		prd.[BreakoutRejectLogs],
		prd.[ManualRejectLogs],
		prd.[OtherRejectLogs],
		prd.[ILOCSetpointTarget],
		prd.[ILOCSetpointAverage],
		prd.[ILOCSetpointSampleCount],
		prd.[ILOCActualAverage],
		prd.[ILOCActualSampleCount],
		prd.[ts],
		prd.[deleteflag],
		prd.[RcdIdx],
		@SiteId AS SITE_DIMENSION_SiteId,
		ld.CentralLineId AS LINE_DIMENSION_CentralLineId
		FROM  @ProductionRawdataCvtg prd
		JOIN dbo.LINE_DIMENSION ld ON prd.PLID = ld.PLId AND ld.SITE_DIMENSION_SiteId = @SiteId
		WHERE NOT EXISTS (  SELECT * 
							FROM dbo.OpsDB_Production_Data_Cvtg u 
							WHERE
							u.RCDIDX				= prd.RcdIdx AND 
							u.SITE_DIMENSION_SiteId = ld.SITE_DIMENSION_SiteId  AND
							u.LINE_DIMENSION_CentralLineId	= ld.CentralLineId
							) 




Update T SET
	T.[SITE]                                   =                               S.[SITE],
	T.[ProcessOrder]                           =                               S.[ProcessOrder],
	T.[PLId]                                   =                               S.[PLId],
	T.[PUId]                                   =                               S.[PUId],
	T.[EventId]                                =                               S.[EventId],
	T.[StartTime]                              =                               S.[StartTime],
	T.[EndTime]                                =                               S.[EndTime],
	T.[StartTimeUTC]                           =                               S.[StartTimeUTC],
	T.[EndTimeUTC]                             =                               S.[EndTimeUTC],
	T.[ProdId]                                 =                               S.[ProdId],
	T.[PLDesc]                                 =                               S.[PLDesc],
	T.[ReliabilityPUID]                        =                               S.[ReliabilityPUID],
	T.[PUDesc]                                 =                               S.[PUDesc],
	T.[ShiftDesc]                              =                               S.[ShiftDesc],
	T.[TeamDesc]                               =                               S.[TeamDesc],
	T.[ProdCode]                               =                               S.[ProdCode],
	T.[ProdDesc]                               =                               S.[ProdDesc],
	T.[ProdFamily]                             =                               S.[ProdFamily],
	T.[ProdGroup]                              =                               S.[ProdGroup],
	T.[PPId]                                   =                               S.[PPId],
	T.[POStatus]                               =                               S.[POStatus],
	T.[PPStatusId]                             =                               S.[PPStatusId],
	T.[BatchNumber]                            =                               S.[BatchNumber],
	T.[TotalUnits]                             =                               S.[TotalUnits],
	T.[GoodUnits]                              =                               S.[GoodUnits],
	T.[RejectUnits]                            =                               S.[RejectUnits],
	T.[WebWidth]                               =                               S.[WebWidth],
	T.[SheetWidth]                             =                               S.[SheetWidth],
	T.[LineSpeedIdeal]                         =                               S.[LineSpeedIdeal],
	T.[LineSpeedTarget]                        =                               S.[LineSpeedTarget],
	T.[LineSpeedAvg]                           =                               S.[LineSpeedAvg],
	T.[TargetLineSpeed]                        =                               S.[TargetLineSpeed],
	T.[LineStatus]                             =                               S.[LineStatus],
	T.[RollsPerLog]                            =                               S.[RollsPerLog],
	T.[RollsInPack]                            =                               S.[RollsInPack],
	T.[PacksInBundle]                          =                               S.[PacksInBundle],
	T.[CartonsInCase]                          =                               S.[CartonsInCase],
	T.[SheetCount]                             =                               S.[SheetCount],
	T.[ShipUnit]                               =                               S.[ShipUnit],
	T.[CalendarRuntime]                        =                               S.[CalendarRuntime],
	T.[ProductionRuntime]                      =                               S.[ProductionRuntime],
	T.[PlanningRuntime]                        =                               S.[PlanningRuntime],
	T.[OperationsRuntime]                      =                               S.[OperationsRuntime],
	T.[SheetLength]                            =                               S.[SheetLength],
	T.[StatFactor]                             =                               S.[StatFactor],
	T.[TargetUnits]                            =                               S.[TargetUnits],
	T.[ActualUnits]                            =                               S.[ActualUnits],
	T.[OperationsTargetUnits]                  =                               S.[OperationsTargetUnits],
	T.[HolidayCurtailDT]                       =                               S.[HolidayCurtailDT],
	T.[PlninterventionDT]                      =                               S.[PlninterventionDT],
	T.[ChangeOverDT]                           =                               S.[ChangeOverDT],
	T.[HygCleaningDT]                          =                               S.[HygCleaningDT],
	T.[EOProjectsDT]                           =                               S.[EOProjectsDT],
	T.[UnscheduledDT]                          =                               S.[UnscheduledDT],
	T.[CLAuditsDT]                             =                               S.[CLAuditsDT],
	T.[IdealUnits]                             =                               S.[IdealUnits],
	T.[RollWidth2Stage]                        =                               S.[RollWidth2Stage],
	T.[RollWidth3Stage]                        =                               S.[RollWidth3Stage],
	T.[SplitUptime]                            =                               S.[SplitUptime],
	T.[Runtime]                                =                               S.[Runtime],
	T.[CnvtLineSpeedToSheetLength]             =                               S.[CnvtLineSpeedToSheetLength],
	T.[CnvtParentRollWidthToSheetWidth]        =                               S.[CnvtParentRollWidthToSheetWidth],
	T.[DefaultPMRollWidth]                     =                               S.[DefaultPMRollWidth],
	T.[LineSpeedUOM]                           =                               S.[LineSpeedUOM],
	T.[SheetLengthSpec]                        =                               S.[SheetLengthSpec],
	T.[SheetLengthSpecUOM]                     =                               S.[SheetLengthSpecUOM],
	T.[SheetWidthSpec]                         =                               S.[SheetWidthSpec],
	T.[SheetWidthSpecUOM]                      =                               S.[SheetWidthSpecUOM],
	T.[PlannedRejectLogs]                      =                               S.[PlannedRejectLogs],
	T.[UnplannedRejectLogs]                    =                               S.[UnplannedRejectLogs],
	T.[BreakoutRejectLogs]                     =                               S.[BreakoutRejectLogs],
	T.[ManualRejectLogs]                       =                               S.[ManualRejectLogs],
	T.[OtherRejectLogs]                        =                               S.[OtherRejectLogs],
	T.[ILOCSetpointTarget]                     =                               S.[ILOCSetpointTarget],
	T.[ILOCSetpointAverage]                    =                               S.[ILOCSetpointAverage],
	T.[ILOCSetpointSampleCount]                =                               S.[ILOCSetpointSampleCount],
	T.[ILOCActualAverage]                      =                               S.[ILOCActualAverage],
	T.[ILOCActualSampleCount]                  =                               S.[ILOCActualSampleCount],
	T.[ts]                                     =                               S.[ts],
	T.[deleteflag]                             =                               S.[deleteflag]		
from dbo.OpsDB_Production_Data_Cvtg T 
JOIN (
                SELECT                              
					prd.[SITE],
					prd.[ProcessOrder],
					prd.[PLId],
					prd.[PUId],
					prd.[EventId],
					prd.[StartTime],
					prd.[EndTime],
					prd.[StartTimeUTC],
					prd.[EndTimeUTC],
					prd.[ProdId],
					prd.[PLDesc],
					prd.[ReliabilityPUID],
					prd.[PUDesc],
					prd.[ShiftDesc],
					prd.[TeamDesc],
					prd.[ProdCode],
					prd.[ProdDesc],
					prd.[ProdFamily],
					prd.[ProdGroup],
					prd.[PPId],
					prd.[POStatus],
					prd.[PPStatusId],
					prd.[BatchNumber],
					prd.[TotalUnits],
					prd.[GoodUnits],
					prd.[RejectUnits],
					prd.[WebWidth],
					prd.[SheetWidth],
					prd.[LineSpeedIdeal],
					prd.[LineSpeedTarget],
					prd.[LineSpeedAvg],
					prd.[TargetLineSpeed],
					prd.[LineStatus],
					prd.[RollsPerLog],
					prd.[RollsInPack],
					prd.[PacksInBundle],
					prd.[CartonsInCase],
					prd.[SheetCount],
					prd.[ShipUnit],
					prd.[CalendarRuntime],
					prd.[ProductionRuntime],
					prd.[PlanningRuntime],
					prd.[OperationsRuntime],
					prd.[SheetLength],
					prd.[StatFactor],
					prd.[TargetUnits],
					prd.[ActualUnits],
					prd.[OperationsTargetUnits],
					prd.[HolidayCurtailDT],
					prd.[PlninterventionDT],
					prd.[ChangeOverDT],
					prd.[HygCleaningDT],
					prd.[EOProjectsDT],
					prd.[UnscheduledDT],
					prd.[CLAuditsDT],
					prd.[IdealUnits],
					prd.[RollWidth2Stage],
					prd.[RollWidth3Stage],
					prd.[SplitUptime],
					prd.[Runtime],
					prd.[CnvtLineSpeedToSheetLength],
					prd.[CnvtParentRollWidthToSheetWidth],
					prd.[DefaultPMRollWidth],
					prd.[LineSpeedUOM],
					prd.[SheetLengthSpec],
					prd.[SheetLengthSpecUOM],
					prd.[SheetWidthSpec],
					prd.[SheetWidthSpecUOM],
					prd.[PlannedRejectLogs],
					prd.[UnplannedRejectLogs],
					prd.[BreakoutRejectLogs],
					prd.[ManualRejectLogs],
					prd.[OtherRejectLogs],
					prd.[ILOCSetpointTarget],
					prd.[ILOCSetpointAverage],
					prd.[ILOCSetpointSampleCount],
					prd.[ILOCActualAverage],
					prd.[ILOCActualSampleCount],
					prd.[ts],
					prd.[deleteflag],
					prd.[RcdIdx],
					@SiteId AS SITE_DIMENSION_SiteId,
					ld.CentralLineId AS LINE_DIMENSION_CentralLineId
                FROM @ProductionRawdataCvtg prd
				JOIN dbo.LINE_DIMENSION ld ON prd.PLID = ld.PLId AND ld.SITE_DIMENSION_SiteId = @SiteId
) S ON (
			T.SITE_DIMENSION_SiteId			= s.SITE_DIMENSION_SiteId AND
			T.LINE_DIMENSION_CentralLineId	= S.LINE_DIMENSION_CentralLineId AND
			T.RcdIdx						= s.RcdIdx	
	    )


	UPDATE [dbo].[Transfer_Parameter_Data]
		SET LastModifytime = ( SELECT MAX(TS) FROM @ProductionRawdataCvtg )
	WHERE TableName = 'OpsDB_Production_Data_Cvtg'
	AND SiteId = @SiteId

RETURN
;
GO

GRANT EXEC ON TYPE::[dbo].[OpsDB_Production_Data_Cvtg_Type]  TO [LocalUser]
GO

GRANT EXECUTE ON OBJECT ::[dbo].splocal_InsertProductionRawDataCvtg  TO [LocalUser]
GO