--DROP PROCEDURE splocal_InsertDowntimeRawData
--GO

CREATE PROCEDURE splocal_InsertDowntimeRawData
  @DownTimeRawdata [dbo].[OpsDB_DowntimeUptime_Data_Type] READONLY
AS
	DECLARE @SiteId INTEGER

	SELECT TOP 1 @SiteId = sd.SiteId
	FROM @DownTimeRawdata dtd
	JOIN SITE_DIMENSION sd ON dtd.DataServerName = sd.DataServerName

	INSERT INTO dbo.OpsDB_DowntimeUptime_Data (
		[StartTime],
		[EndTime],
		[StartTimeUTC],
		[EndTimeUTC],
		[Duration],
		[Total_Uptime],
		[Uptime],
		[Fault],
		[FaultGlobal],
		[FaultCode],
		[Reason1Id],
		[Reason1],
		[Reason1Global],
		[Reason1Code],
		[Reason1Category],
		[Reason1CategoryGlobal],
		[Reason2Id],
		[Reason2],
		[Reason2Global],
		[Reason2Code],
		[Reason2Category],
		[Reason2CategoryGlobal],
		[Reason3Id],
		[Reason3],
		[Reason3Global],
		[Reason3Code],
		[Reason3Category],
		[Reason3CategoryGlobal],
		[Reason4Id],
		[Reason4],
		[Reason4Global],
		[Reason4Code],
		[Reason4Category],
		[Reason4CategoryGlobal],
		[Action1],
		[Action1Code],
		[Action2],
		[Action2Code],
		[Action3],
		[Action3Code],
		[Action4],
		[Action4Code],
		[Planned],
		[DChangeOverAlltypes],
		[DChangeOverPackingCO],
		[Location],
		[LocationGlobal],
		[ProdDesc],
		[ProdDescGlobal],
		[ProdCode],
		[ProdFam],
		[ProdGroup],
		[ProdGroupGlobal],
		[ProcessOrder],
		[TeamDesc],
		[ShiftDesc],
		[LineStatus],
		[DTStatus],
		[Comments],
		[MainComments],
		[PLDesc],
		[PUDesc],
		[PLDescGlobal],
		[PUDescGlobal],
		[PUID],
		[PLID],
		[BreakDown],
		[ProcFailure],
		[TransferFlag],
		[DeleteFlag],
		[Site],
		[TEDetId],
		[Ts],
		[IsContraint],
		[ProductionDay],
		[IsStarved],
		[IsBlocked],
		[ManualStops],
		[MinorStop],
		[MajorStop],
		[ZoneDesc],
		[ZoneGrpDesc],
		[LineGroup],
		[StopsEquipFails],
		[StopsELP],
		[StopsScheduled],
		[StopsUnscheduled],
		[StopsUnscheduledInternal],
		[StopsUnscheduledBS],
		[StopsBlockedStarved],
		[ERTD_ID],
		[RawRateloss],
		[RateLossRatio],
		[CommentId],
		[CommentModifOn],
		[Comment_Rtf],
		[Repulper_Tons],
		[SITE_DIMENSION_SiteId],
		[LINE_DIMENSION_CentralLineId],
		[RcdIdx]
	)
	SELECT
		drd.[StartTime],
		drd.[EndTime],
		drd.[StartTimeUTC],
		drd.[EndTimeUTC],
		drd.[Duration],
		drd.[Total_Uptime],
		drd.[Uptime],
		drd.[Fault],
		drd.[FaultGlobal],
		drd.[FaultCode],
		drd.[Reason1Id],
		drd.[Reason1],
		drd.[Reason1Global],
		drd.[Reason1Code],
		drd.[Reason1Category],
		drd.[Reason1CategoryGlobal],
		drd.[Reason2Id],
		drd.[Reason2],
		drd.[Reason2Global],
		drd.[Reason2Code],
		drd.[Reason2Category],
		drd.[Reason2CategoryGlobal],
		drd.[Reason3Id],
		drd.[Reason3],
		drd.[Reason3Global],
		drd.[Reason3Code],
		drd.[Reason3Category],
		drd.[Reason3CategoryGlobal],
		drd.[Reason4Id],
		drd.[Reason4],
		drd.[Reason4Global],
		drd.[Reason4Code],
		drd.[Reason4Category],
		drd.[Reason4CategoryGlobal],
		drd.[Action1],
		drd.[Action1Code],
		drd.[Action2],
		drd.[Action2Code],
		drd.[Action3],
		drd.[Action3Code],
		drd.[Action4],
		drd.[Action4Code],
		drd.[Planned],
		drd.[DChangeOverAlltypes],
		drd.[DChangeOverPackingCO],
		drd.[Location],
		drd.[LocationGlobal],
		drd.[ProdDesc],
		drd.[ProdDescGlobal],
		drd.[ProdCode],
		drd.[ProdFam],
		drd.[ProdGroup],
		drd.[ProdGroupGlobal],
		drd.[ProcessOrder],
		drd.[TeamDesc],
		drd.[ShiftDesc],
		drd.[LineStatus],
		drd.[DTStatus],
		drd.[Comments],
		drd.[MainComments],
		drd.[PLDesc],
		drd.[PUDesc],
		drd.[PLDescGlobal],
		drd.[PUDescGlobal],
		drd.[PUID],
		drd.[PLID],
		drd.[BreakDown],
		drd.[ProcFailure],
		drd.[TransferFlag],
		drd.[DeleteFlag],
		drd.[Site],
		drd.[TEDetId],
		drd.[Ts],
		drd.[IsContraint],
		CONVERT(DATETIME,drd.[ProductionDay]),
		drd.[IsStarved],
		drd.[IsBlocked],
		drd.[ManualStops],
		drd.[MinorStop],
		drd.[MajorStop],
		drd.[ZoneDesc],
		drd.[ZoneGrpDesc],
		drd.[LineGroup],
		drd.[StopsEquipFails],
		drd.[StopsELP],
		drd.[StopsScheduled],
		drd.[StopsUnscheduled],
		drd.[StopsUnscheduledInternal],
		drd.[StopsUnscheduledBS],
		drd.[StopsBlockedStarved],
		drd.[ERTD_ID],
		drd.[RawRateloss],
		drd.[RateLossRatio],
		drd.[CommentId],
		drd.[CommentModifOn],
		drd.[Comment_Rtf],
		drd.[Repulper_Tons],
		@SiteId AS SITE_DIMENSION_SiteId,
		ld.CentralLineId AS LINE_DIMENSION_CentralLineId,
		drd.[RcdIdx]
		FROM  @DownTimeRawdata drd
		JOIN dbo.LINE_DIMENSION ld ON drd.PLID = ld.PLId AND ld.SITE_DIMENSION_SiteId = @SiteId
		WHERE NOT EXISTS (  SELECT *
							FROM dbo.OpsDB_DowntimeUptime_Data u
							WHERE
							u.RCDIDX				= drd.RcdIdx AND
							u.SITE_DIMENSION_SiteId = ld.SITE_DIMENSION_SiteId  AND
							u.LINE_DIMENSION_CentralLineId	= ld.CentralLineId
							)

Update T SET
				T.[StartTime]								   = s.[StartTime]		   ,
				T.[EndTime]										= s.[EndTime],
				T.[StartTimeUTC]								= s.[StartTimeUTC],
				T.[EndTimeUTC]									= s.[EndTimeUTC],
				T.[Duration]									= s.[Duration],
				T.[Total_Uptime]								= s.[Total_Uptime],
				T.[Uptime]										= s.[Uptime],
				T.[Fault]										= s.[Fault],
				T.[FaultGlobal]									= s.[FaultGlobal],
				T.[FaultCode]									= s.[FaultCode],
				T.[Reason1Id]									= s.[Reason1Id],
				T.[Reason1]										= s.[Reason1],
				T.[Reason1Global]								= s.[Reason1Global],
				T.[Reason1Code]									= s.[Reason1Code],
				T.[Reason1Category]								= s.[Reason1Category],
				T.[Reason1CategoryGlobal]						= s.[Reason1CategoryGlobal],
				T.[Reason2Id]									= s.[Reason2Id],
				T.[Reason2]										= s.[Reason2],
				T.[Reason2Global]								= s.[Reason2Global],
				T.[Reason2Code]									= s.[Reason2Code],
				T.[Reason2Category]								= s.[Reason2Category],
				T.[Reason2CategoryGlobal]						= s.[Reason2CategoryGlobal],
				T.[Reason3Id]									= s.[Reason3Id],
				T.[Reason3]										= s.[Reason3],
				T.[Reason3Global]								= s.[Reason3Global],
				T.[Reason3Code]									= s.[Reason3Code],
				T.[Reason3Category]								= s.[Reason3Category],
				T.[Reason3CategoryGlobal]						= s.[Reason3CategoryGlobal],
				T.[Reason4Id]									= s.[Reason4Id],
				T.[Reason4]										= s.[Reason4],
				T.[Reason4Global]								= s.[Reason4Global],
				T.[Reason4Code]									= s.[Reason4Code],
				T.[Reason4Category]								= s.[Reason4Category],
				T.[Reason4CategoryGlobal]						= s.[Reason4CategoryGlobal],
				T.[Action1]										= s.[Action1],
				T.[Action1Code]									= s.[Action1Code],
				T.[Action2]										= s.[Action2],
				T.[Action2Code]									= s.[Action2Code],
				T.[Action3]										= s.[Action3],
				T.[Action3Code]									= s.[Action3Code],
				T.[Action4]										= s.[Action4],
				T.[Action4Code]									= s.[Action4Code],
				T.[Planned]										= s.[Planned],
				T.[DChangeOverAlltypes]							= s.[DChangeOverAlltypes],
				T.[DChangeOverPackingCO]						= s.[DChangeOverPackingCO],
				T.[Location]									= s.[Location],
				T.[LocationGlobal]								= s.[LocationGlobal],
				T.[ProdDesc]									= s.[ProdDesc],
				T.[ProdDescGlobal]								= s.[ProdDescGlobal],
				T.[ProdCode]									= s.[ProdCode],
				T.[ProdFam]										= s.[ProdFam],
				T.[ProdGroup]									= s.[ProdGroup],
				T.[ProdGroupGlobal]								= s.[ProdGroupGlobal],
				T.[ProcessOrder]								= s.[ProcessOrder],
				T.[TeamDesc]									= s.[TeamDesc],
				T.[ShiftDesc]									= s.[ShiftDesc],
				T.[LineStatus]									= s.[LineStatus],
				T.[DTStatus]									= s.[DTStatus],
				T.[Comments]									= s.[Comments],
				T.[MainComments]								= s.[MainComments],
				T.[PLDesc]										= s.[PLDesc],
				T.[PUDesc]										= s.[PUDesc],
				T.[PLDescGlobal]								= s.[PLDescGlobal],
				T.[PUDescGlobal]								= s.[PUDescGlobal],
				T.[PUID]										= s.[PUID],
				T.[PLID]										= s.[PLID],
				T.[BreakDown]									= s.[BreakDown],
				T.[ProcFailure]									= s.[ProcFailure],
				T.[TransferFlag]								= s.[TransferFlag],
				T.[DeleteFlag]									= s.[DeleteFlag],
				T.[Site]										= s.[Site],
				T.[TEDetId]										= s.[TEDetId],
				T.[Ts]											= s.[Ts],
				T.[IsContraint]									= s.[IsContraint],
				T.[ProductionDay]								= s.[ProductionDay],
				T.[IsStarved]									= s.[IsStarved],
				T.[IsBlocked]									= s.[IsBlocked],
				T.[ManualStops]									= s.[ManualStops],
				T.[MinorStop]									= s.[MinorStop],
				T.[MajorStop]									= s.[MajorStop],
				T.[ZoneDesc]									= s.[ZoneDesc],
				T.[ZoneGrpDesc]									= s.[ZoneGrpDesc],
				T.[LineGroup]									= s.[LineGroup],
				T.[StopsEquipFails]								= s.[StopsEquipFails],
				T.[StopsELP]									= s.[StopsELP],
				T.[StopsScheduled]								= s.[StopsScheduled],
				T.[StopsUnscheduled]							= s.[StopsUnscheduled],
				T.[StopsUnscheduledInternal]					= s.[StopsUnscheduledInternal],
				T.[StopsUnscheduledBS]							= s.[StopsUnscheduledBS],
				T.[StopsBlockedStarved]							= s.[StopsBlockedStarved],
				T.[ERTD_ID]										= s.[ERTD_ID],
				T.[RawRateloss]									= s.[RawRateloss],
				T.[RateLossRatio]								= s.[RateLossRatio],
				T.[CommentId]									= s.[CommentId],
				T.[CommentModifOn]								= s.[CommentModifOn],
				T.[Comment_Rtf]									= s.[Comment_Rtf],
				T.[Repulper_Tons]								= s.[Repulper_Tons]
from dbo.OpsDB_DowntimeUptime_Data T
JOIN (
				SELECT
				StartTime,
				EndTime,
				StartTimeUTC,
				EndTimeUTC,
				Duration,
				Total_Uptime,
				Uptime,
				Fault,
				FaultGlobal,
				FaultCode,
				Reason1Id,
				Reason1,
				Reason1Global,
				Reason1Code,
				Reason1Category,
				Reason1CategoryGlobal,
				Reason2Id,
				Reason2,
				Reason2Global,
				Reason2Code,
				Reason2Category,
				Reason2CategoryGlobal,
				Reason3Id,
				Reason3,
				Reason3Global,
				Reason3Code,
				Reason3Category,
				Reason3CategoryGlobal,
				Reason4Id,
				Reason4,
				Reason4Global,
				Reason4Code,
				Reason4Category,
				Reason4CategoryGlobal,
				Action1,
				Action1Code,
				Action2,
				Action2Code,
				Action3,
				Action3Code,
				Action4,
				Action4Code,
				Planned,
				DChangeOverAlltypes,
				DChangeOverPackingCO,
				Location,
				LocationGlobal,
				ProdDesc,
				ProdDescGlobal,
				ProdCode,
				ProdFam,
				ProdGroup,
				ProdGroupGlobal,
				ProcessOrder,
				TeamDesc,
				ShiftDesc,
				LineStatus,
				DTStatus,
				Comments,
				MainComments,
				PLDesc,
				PUDesc,
				PLDescGlobal,
				PUDescGlobal,
				PUID,
				d.PLID,
				BreakDown,
				ProcFailure,
				TransferFlag,
				DeleteFlag,
				Site,
				TEDetId,
				Ts,
				IsContraint,
				ProductionDay,
				IsStarved,
				IsBlocked,
				ManualStops,
				MinorStop,
				MajorStop,
				ZoneDesc,
				ZoneGrpDesc,
				LineGroup,
				StopsEquipFails,
				StopsELP,
				StopsScheduled,
				StopsUnscheduled,
				StopsUnscheduledInternal,
				StopsUnscheduledBS,
				StopsBlockedStarved,
				ERTD_ID,
				RawRateloss,
				RateLossRatio,
				CommentId,
				CommentModifOn,
				Comment_Rtf,
				Repulper_Tons,
				ld.SITE_DIMENSION_SiteId,
				ld.CentralLineId,
				RcdIdx
				FROM @DownTimeRawdata d
				JOIN dbo.LINE_DIMENSION ld ON d.PLID = ld.PLId AND ld.SITE_DIMENSION_SiteId = @SiteId
) S ON (
			T.SITE_DIMENSION_SiteId			= s.SITE_DIMENSION_SiteId AND
			T.LINE_DIMENSION_CentralLineId	= s.CentralLineid AND
			T.RcdIdx						= s.RcdIdx
		)

	UPDATE [dbo].[Transfer_Parameter_Data]
		SET LastModifytime = ( SELECT MAX(TS) FROM @DownTimeRawdata )
	WHERE TableName = 'OpsDB_DowntimeUptime_Data'
	AND SiteId = @SiteId

RETURN
GO

GRANT EXEC ON TYPE::[dbo].[OpsDB_DowntimeUptime_Data_Type]  TO [LocalUser]
GO

GRANT EXECUTE ON OBJECT ::[dbo].splocal_InsertDowntimeRawData  TO [LocalUser]
GO



