--DROP PROCEDURE splocal_InsertQACLRawData;
--GO




CREATE PROCEDURE splocal_InsertQACLRawData
   @QACLTaksRawdata [dbo].[OpsDB_QA_CL_Data_Type] READONLY
AS

	DECLARE @SiteId INTEGER

	SELECT TOP 1 @SiteId = sd.SiteId 
	FROM @QACLTaksRawdata qa
	JOIN SITE_DIMENSION sd ON qa.DataServerName = sd.DataServerName
	
	INSERT INTO [dbo].[OpsDB_VariablesTasks_RawData] (
	[VarId]						,
	[PLId]						,
	[PLDesc]					,
	[PLDescGlobal]				,
	[PUId]						,
	[PUDesc]					,
	[PUDescGlobal]				,
	[PUGDesc]					,
	[VarDesc]					,
	[VarDescGlobal]				,
	[ProdId]					,
	[Frequency]					,
	[ProdCode]					,
	[ProdDesc]					,
	[ProdDescGlobal]			,
	[ProcessOrder]				,
	[Result]					,
	[LReject]					,
	[UReject]					,
	[LWarning]					,
	[UWarning]					,
	[LUser]						,
	[UUser]						,
	[Target]					,
	[LControl]					,
	[UControl]					,
	[EffectiveDate]				,
	[Defect]					,
	[Deptid]					,
	[DeptDesc]					,
	[MasterUnit]				,
	[MasterUnitDesc]			,
	[MasterUnitDescGlobal]		,
	[UserDesc]					,
	[TeamDesc]					,
	[ShiftDesc]					,
	[RouteDesc]					,
	[ProductGrpDesc]			,
	[ProductGrpDescGlobal]		,
	[LineStatus]				,
	[DataType]					,
	[ProdDay]					,
	[EntryOn]					,
	[ResultOn]					,
	[ModifiedOn]				,
	[NextStartDate]				,
	[SamplesTaken]				,
	[OnTime]					,
	[DoneLate]					,
	[Canceled]					,
	[UDEDesc]					,
	[SheetDesc]					,
	[Site]						,
	[StubberUser]				,
	[FACT_UDPs_Idx]				,
	[ZoneDesc]					,
	[ZoneGrpDesc]				,
	[CommentText]				,
	[CommentId]					,
	[CommentModifOn]			,
	[Comment_Rtf]				,
	[SITE_DIMENSION_SiteId]		,
	[LINE_DIMENSION_CentralLineId]		,
	[RcdIdx]
	)	
	SELECT
	qat.[VarId]						,
	qat.[PLId]						,
	qat.[PLDesc]					,
	qat.[PLDescGlobal]				,
	qat.[PUId]						,
	qat.[PUDesc]					,
	qat.[PUDescGlobal]				,
	qat.[PUGDesc]					,
	qat.[VarDesc]					,
	qat.[VarDescGlobal]				,
	qat.[ProdId]					,
	qat.[Frequency]					,
	qat.[ProdCode]					,
	qat.[ProdDesc]					,
	qat.[ProdDescGlobal]			,
	qat.[ProcessOrder]				,
	qat.[Result]					,
	qat.[LReject]					,
	qat.[UReject]					,
	qat.[LWarning]					,
	qat.[UWarning]					,
	qat.[LUser]						,
	qat.[UUser]						,
	qat.[Target]					,
	qat.[LControl]					,
	qat.[UControl]					,
	qat.[EffectiveDate]				,
	qat.[Defect]					,
	qat.[Deptid]					,
	qat.[DeptDesc]					,
	qat.[MasterUnit]				,
	qat.[MasterUnitDesc]			,
	qat.[MasterUnitDescGlobal]		,
	qat.[UserDesc]					,
	qat.[TeamDesc]					,
	qat.[ShiftDesc]					,
	qat.[RouteDesc]					,
	qat.[ProductGrpDesc]			,
	qat.[ProductGrpDescGlobal]		,
	qat.[LineStatus]				,
	qat.[DataType]					,
	qat.[ProdDay]					,
	qat.[EntryOn]					,
	qat.[ResultOn]					,
	qat.[ModifiedOn]				,
	qat.[NextStartDate]				,
	qat.[SamplesTaken]				,
	qat.[OnTime]					,
	qat.[DoneLate]					,
	qat.[Canceled]					,
	qat.[UDEDesc]					,
	qat.[SheetDesc]					,
	qat.[Site]						,
	qat.[StubberUser]				,
	fu.[CentralIdx]					,
	qat.[ZoneDesc]					,
	qat.[ZoneGrpDesc]				,
	qat.[CommentText]				,
	qat.[CommentId]					,
	qat.[CommentModifOn]			,
	qat.[Comment_Rtf]				,
	@SiteId AS SITE_DIMENSION_SiteId		,
	ld.CentralLineId AS LINE_DIMENSION_CentralLineId ,
	qat.[RcdIdx] 
	FROM  @QACLTaksRawdata qat 
	JOIN [dbo].[FACT_UDPs] fu on fu.Idx = qat.FACT_UDPs_Idx AND fu.VALUE='QA'  AND FU.SITE_DIMENSION_SiteId = @SiteId
	JOIN dbo.LINE_DIMENSION ld ON qat.PLID = ld.PLId AND ld.SITE_DIMENSION_SiteId = @SiteId
	WHERE NOT EXISTS (  SELECT * 
							FROM [OpsDB_VariablesTasks_RawData] u 
							WHERE
							u.RCDIDX						= qat.RcdIdx AND 
							u.SITE_DIMENSION_SiteId			= ld.SITE_DIMENSION_SiteId  AND
							u.LINE_DIMENSION_CentralLineId	= ld.CentralLineId
							) 

	
	INSERT INTO [dbo].[OpsDB_CLTasks_RawData] (
	[VarId]							,
	[PLId]							,
	[PLDesc]						,
	[PLDescGlobal]					,
	[PUId]							,
	[PUDesc]						,
	[PUDescGlobal]					,
	[PUGDesc]						,
	[VarDesc]						,
	[VarDescGlobal]					,
	[ProdId]						,
	[Frequency]						,
	[ProdCode]						,
	[ProdDesc]						,
	[ProdDescGlobal]				,
	[ProcessOrder]					,
	[Result]						,
	[LReject]						,
	[UReject]						,
	[LWarning]						,
	[UWarning]						,
	[LUser]							,
	[UUser]							,
	[Target]						,
	[LControl]						,
	[UControl]						,
	[EffectiveDate]					,
	[Defect]						,
	[Deptid]						,
	[DeptDesc]						,
	[MasterUnit]					,
	[MasterUnitDesc]				,
	[MasterUnitDescGlobal]			,
	[UserDesc]						,
	[TeamDesc]						,
	[ShiftDesc]						,
	[RouteDesc]						,
	[ProductGrpDesc]				,
	[ProductGrpDescGlobal]			,
	[LineStatus]					,
	[DataType]						,
	[ProdDay]						,
	[EntryOn]						,
	[ResultOn]						,
	[ModifiedOn]					,
	[NextStartDate]					,
	[SamplesTaken]					,
	[OnTime]						,
	[DoneLate]						,
	[Canceled]						,
	[UDEDesc]						,
	[SheetDesc]						,
	[Site]							,
	[StubberUser]					,
	[FACT_UDPs_Idx]					,
	[ZoneDesc]						,
	[ZoneGrpDesc]					,
	[CommentText]					,
	[CommentId]						,
	[CommentModifOn]				,
	[Comment_Rtf]					,
	[SITE_DIMENSION_SiteId]			,
	[LINE_DIMENSION_CentralLineId]	,
	[RcdIdx]
	)	
	SELECT
	qat.[VarId]						,
	qat.[PLId]						,
	qat.[PLDesc]					,
	qat.[PLDescGlobal]				,
	qat.[PUId]						,
	qat.[PUDesc]					,
	qat.[PUDescGlobal]				,
	qat.[PUGDesc]					,
	qat.[VarDesc]					,
	qat.[VarDescGlobal]				,
	qat.[ProdId]					,
	qat.[Frequency]					,
	qat.[ProdCode]					,
	qat.[ProdDesc]					,
	qat.[ProdDescGlobal]			,
	qat.[ProcessOrder]				,
	qat.[Result]					,
	qat.[LReject]					,
	qat.[UReject]					,
	qat.[LWarning]					,
	qat.[UWarning]					,
	qat.[LUser]						,
	qat.[UUser]						,
	qat.[Target]					,
	qat.[LControl]					,
	qat.[UControl]					,
	qat.[EffectiveDate]				,
	qat.[Defect]					,
	qat.[Deptid]					,
	qat.[DeptDesc]					,
	qat.[MasterUnit]				,
	qat.[MasterUnitDesc]			,
	qat.[MasterUnitDescGlobal]		,
	qat.[UserDesc]					,
	qat.[TeamDesc]					,
	qat.[ShiftDesc]					,
	qat.[RouteDesc]					,
	qat.[ProductGrpDesc]			,
	qat.[ProductGrpDescGlobal]		,
	qat.[LineStatus]				,
	qat.[DataType]					,
	qat.[ProdDay]					,
	qat.[EntryOn]					,
	qat.[ResultOn]					,
	qat.[ModifiedOn]				,
	qat.[NextStartDate]				,
	qat.[SamplesTaken]				,
	qat.[OnTime]					,
	qat.[DoneLate]					,
	qat.[Canceled]					,
	qat.[UDEDesc]					,
	qat.[SheetDesc]					,
	qat.[Site]						,
	qat.[StubberUser]				,
	fu.[CentralIdx]					,
	qat.[ZoneDesc]					,
	qat.[ZoneGrpDesc]				,
	qat.[CommentText]				,
	qat.[CommentId]					,
	qat.[CommentModifOn]			,
	qat.[Comment_Rtf]				,
	@SiteId AS SITE_DIMENSION_SiteId		,
	ld.CentralLineId AS LINE_DIMENSION_CentralLineId ,
	qat.[RcdIdx] 
	FROM  @QACLTaksRawdata qat 
	JOIN [dbo].[FACT_UDPs] fu on fu.Idx = qat.FACT_UDPs_Idx AND fu.VALUE='CL' AND FU.SITE_DIMENSION_SiteId = @SiteId 
	JOIN dbo.LINE_DIMENSION ld ON qat.PLID = ld.PLId AND ld.SITE_DIMENSION_SiteId = @SiteId
	WHERE  NOT EXISTS (  SELECT * 
							FROM [OpsDB_CLTasks_RawData] u 
							WHERE
							u.RCDIDX						= qat.RcdIdx AND 
							u.SITE_DIMENSION_SiteId			= ld.SITE_DIMENSION_SiteId  AND
							u.LINE_DIMENSION_CentralLineId	= ld.CentralLineId
							) 



Update T SET
					T.[VarId]					=      s.[VarId]					,
					T.[PLId]					=      s.[PLId]						,
					T.[PLDesc]					=      s.[PLDesc]					,
					T.[PLDescGlobal]			=      s.[PLDescGlobal]				,
					T.[PUId]					=      s.[PUId]						,
					T.[PUDesc]					=      s.[PUDesc]					,
					T.[PUDescGlobal]			=      s.[PUDescGlobal]				,
					T.[PUGDesc]					=      s.[PUGDesc]					,
					T.[VarDesc]					=      s.[VarDesc]					,
					T.[VarDescGlobal]			=      s.[VarDescGlobal]			,
					T.[ProdId]					=      s.[ProdId]					,
					T.[Frequency]				=      s.[Frequency]				,
					T.[ProdCode]				=      s.[ProdCode]					,
					T.[ProdDesc]				=      s.[ProdDesc]					,
					T.[ProdDescGlobal]			=      s.[ProdDescGlobal]			,
					T.[ProcessOrder]			=      s.[ProcessOrder]				,
					T.[Result]					=      s.[Result]					,
					T.[LReject]					=      s.[LReject]					,
					T.[UReject]					=      s.[UReject]					,
					T.[LWarning]				=      s.[LWarning]					,
					T.[UWarning]				=      s.[UWarning]					,
					T.[LUser]					=      s.[LUser]					,
					T.[UUser]					=      s.[UUser]					,
					T.[Target]					=      s.[Target]					,
					T.[LControl]				=      s.[LControl]					,
					T.[UControl]				=      s.[UControl]					,
					T.[EffectiveDate]			=      s.[EffectiveDate]			,
					T.[Defect]					=      s.[Defect]					,
					T.[Deptid]					=      s.[Deptid]					,
					T.[DeptDesc]				=      s.[DeptDesc]					,
					T.[MasterUnit]				=      s.[MasterUnit]				,
					T.[MasterUnitDesc]			=      s.[MasterUnitDesc]			,
					T.[MasterUnitDescGlobal]	=      s.[MasterUnitDescGlobal]		,
					T.[UserDesc]				=      s.[UserDesc]					,
					T.[TeamDesc]				=      s.[TeamDesc]					,
					T.[ShiftDesc]				=      s.[ShiftDesc]				,
					T.[RouteDesc]				=      s.[RouteDesc]				,
					T.[ProductGrpDesc]			=      s.[ProductGrpDesc]			,
					T.[ProductGrpDescGlobal]	=      s.[ProductGrpDescGlobal]		,
					T.[LineStatus]				=      s.[LineStatus]				,
					T.[DataType]				=      s.[DataType]					,
					T.[ProdDay]					=      s.[ProdDay]					,
					T.[EntryOn]					=      s.[EntryOn]					,
					T.[ResultOn]				=      s.[ResultOn]					,
					T.[ModifiedOn]				=      s.[ModifiedOn]				,
					T.[NextStartDate]			=      s.[NextStartDate]			,
					T.[SamplesTaken]			=      s.[SamplesTaken]				,
					T.[OnTime]					=      s.[OnTime]					,
					T.[DoneLate]				=      s.[DoneLate]					,
					T.[Canceled]				=      s.[Canceled]					,
					T.[UDEDesc]					=      s.[UDEDesc]					,
					T.[SheetDesc]				=      s.[SheetDesc]				,
					T.[Site]					=      s.[Site]						,
					T.[StubberUser]				=      s.[StubberUser]				,
					T.[FACT_UDPs_Idx]			=      s.CentralIdx			,
					T.[ZoneDesc]				=      s.[ZoneDesc]					,
					T.[ZoneGrpDesc]				=      s.[ZoneGrpDesc]				,
					T.[CommentText]				=      s.[CommentText]				,
					T.[CommentId]				=      s.[CommentId]				,
					T.[CommentModifOn]			=      s.[CommentModifOn]			,
					T.[Comment_Rtf]				=      s.[Comment_Rtf]				
					
from [dbo].[OpsDB_VariablesTasks_RawData] T
JOIN (
               SELECT                              
				d.[VarId]					,
				d.[PLId]					,
				[PLDesc]					,
				[PLDescGlobal]				,
				[PUId]						,
				[PUDesc]					,
				[PUDescGlobal]				,
				[PUGDesc]					,
				d.[VarDesc]					,
				[VarDescGlobal]				,
				[ProdId]					,
				[Frequency]					,
				[ProdCode]					,
				[ProdDesc]					,
				[ProdDescGlobal]			,
				[ProcessOrder]				,
				[Result]					,
				[LReject]					,
				[UReject]					,
				[LWarning]					,
				[UWarning]					,
				[LUser]						,
				[UUser]						,
				[Target]					,
				[LControl]					,
				[UControl]					,
				d.[EffectiveDate]			,
				[Defect]					,
				d.[Deptid]					,
				d.[DeptDesc]				,
				[MasterUnit]				,
				[MasterUnitDesc]			,
				[MasterUnitDescGlobal]		,
				[UserDesc]					,
				[TeamDesc]					,
				[ShiftDesc]					,
				[RouteDesc]					,
				[ProductGrpDesc]			,
				[ProductGrpDescGlobal]		,
				[LineStatus]				,
				[DataType]					,
				[ProdDay]					,
				[EntryOn]					,
				[ResultOn]					,
				[ModifiedOn]				,
				[NextStartDate]				,
				[SamplesTaken]				,
				[OnTime]					,
				[DoneLate]					,
				[Canceled]					,
				[UDEDesc]					,
				[SheetDesc]					,
				[Site]						,
				[StubberUser]				,
				fu.[CentralIdx]				,
				[ZoneDesc]					,
				[ZoneGrpDesc]				,
				[CommentText]				,
				[CommentId]					,
				[CommentModifOn]			,
				[Comment_Rtf]				,
				ld.SITE_DIMENSION_SiteId	,
				ld.CentralLineId					,
				RcdIdx	
                FROM @QACLTaksRawdata d 
				JOIN [dbo].[FACT_UDPs] fu on fu.Idx = d.FACT_UDPs_Idx AND fu.VALUE='QA' AND  fu.SITE_DIMENSION_SiteId = @SiteId
				JOIN dbo.LINE_DIMENSION ld ON d.PLID = ld.PLId AND ld.SITE_DIMENSION_SiteId = @SiteId
) S ON (
						T.[SITE_DIMENSION_SiteId]		= s.SITE_DIMENSION_SiteId AND
						T.LINE_DIMENSION_CentralLineId	= s.CentralLineid AND
						T.RcdIdx						= s.RcdIdx	
	    )

Update T SET
					T.[VarId]					=      s.[VarId]					,
					T.[PLId]					=      s.[PLId]						,
					T.[PLDesc]					=      s.[PLDesc]					,
					T.[PLDescGlobal]			=      s.[PLDescGlobal]				,
					T.[PUId]					=      s.[PUId]						,
					T.[PUDesc]					=      s.[PUDesc]					,
					T.[PUDescGlobal]			=      s.[PUDescGlobal]				,
					T.[PUGDesc]					=      s.[PUGDesc]					,
					T.[VarDesc]					=      s.[VarDesc]					,
					T.[VarDescGlobal]			=      s.[VarDescGlobal]			,
					T.[ProdId]					=      s.[ProdId]					,
					T.[Frequency]				=      s.[Frequency]				,
					T.[ProdCode]				=      s.[ProdCode]					,
					T.[ProdDesc]				=      s.[ProdDesc]					,
					T.[ProdDescGlobal]			=      s.[ProdDescGlobal]			,
					T.[ProcessOrder]			=      s.[ProcessOrder]				,
					T.[Result]					=      s.[Result]					,
					T.[LReject]					=      s.[LReject]					,
					T.[UReject]					=      s.[UReject]					,
					T.[LWarning]				=      s.[LWarning]					,
					T.[UWarning]				=      s.[UWarning]					,
					T.[LUser]					=      s.[LUser]					,
					T.[UUser]					=      s.[UUser]					,
					T.[Target]					=      s.[Target]					,
					T.[LControl]				=      s.[LControl]					,
					T.[UControl]				=      s.[UControl]					,
					T.[EffectiveDate]			=      s.[EffectiveDate]			,
					T.[Defect]					=      s.[Defect]					,
					T.[Deptid]					=      s.[Deptid]					,
					T.[DeptDesc]				=      s.[DeptDesc]					,
					T.[MasterUnit]				=      s.[MasterUnit]				,
					T.[MasterUnitDesc]			=      s.[MasterUnitDesc]			,
					T.[MasterUnitDescGlobal]	=      s.[MasterUnitDescGlobal]		,
					T.[UserDesc]				=      s.[UserDesc]					,
					T.[TeamDesc]				=      s.[TeamDesc]					,
					T.[ShiftDesc]				=      s.[ShiftDesc]				,
					T.[RouteDesc]				=      s.[RouteDesc]				,
					T.[ProductGrpDesc]			=      s.[ProductGrpDesc]			,
					T.[ProductGrpDescGlobal]	=      s.[ProductGrpDescGlobal]		,
					T.[LineStatus]				=      s.[LineStatus]				,
					T.[DataType]				=      s.[DataType]					,
					T.[ProdDay]					=      s.[ProdDay]					,
					T.[EntryOn]					=      s.[EntryOn]					,
					T.[ResultOn]				=      s.[ResultOn]					,
					T.[ModifiedOn]				=      s.[ModifiedOn]				,
					T.[NextStartDate]			=      s.[NextStartDate]			,
					T.[SamplesTaken]			=      s.[SamplesTaken]				,
					T.[OnTime]					=      s.[OnTime]					,
					T.[DoneLate]				=      s.[DoneLate]					,
					T.[Canceled]				=      s.[Canceled]					,
					T.[UDEDesc]					=      s.[UDEDesc]					,
					T.[SheetDesc]				=      s.[SheetDesc]				,
					T.[Site]					=      s.[Site]						,
					T.[StubberUser]				=      s.[StubberUser]				,
					T.[FACT_UDPs_Idx]			=      s.CentralIdx					,
					T.[ZoneDesc]				=      s.[ZoneDesc]					,
					T.[ZoneGrpDesc]				=      s.[ZoneGrpDesc]				,
					T.[CommentText]				=      s.[CommentText]				,
					T.[CommentId]				=      s.[CommentId]				,
					T.[CommentModifOn]			=      s.[CommentModifOn]			,
					T.[Comment_Rtf]				=      s.[Comment_Rtf]				
					
from [dbo].[OpsDB_CLTasks_RawData] T
JOIN (
               SELECT                              
				d.[VarId]					,
				d.[PLId]					,
				[PLDesc]					,
				[PLDescGlobal]				,
				[PUId]						,
				[PUDesc]					,
				[PUDescGlobal]				,
				[PUGDesc]					,
				d.[VarDesc]					,
				[VarDescGlobal]				,
				[ProdId]					,
				[Frequency]					,
				[ProdCode]					,
				[ProdDesc]					,
				[ProdDescGlobal]			,
				[ProcessOrder]				,
				[Result]					,
				[LReject]					,
				[UReject]					,
				[LWarning]					,
				[UWarning]					,
				[LUser]						,
				[UUser]						,
				[Target]					,
				[LControl]					,
				[UControl]					,
				d.[EffectiveDate]			,
				[Defect]					,
				d.[Deptid]					,
				d.[DeptDesc]				,
				[MasterUnit]				,
				[MasterUnitDesc]			,
				[MasterUnitDescGlobal]		,
				[UserDesc]					,
				[TeamDesc]					,
				[ShiftDesc]					,
				[RouteDesc]					,
				[ProductGrpDesc]			,
				[ProductGrpDescGlobal]		,
				[LineStatus]				,
				[DataType]					,
				[ProdDay]					,
				[EntryOn]					,
				[ResultOn]					,
				[ModifiedOn]				,
				[NextStartDate]				,
				[SamplesTaken]				,
				[OnTime]					,
				[DoneLate]					,
				[Canceled]					,
				[UDEDesc]					,
				[SheetDesc]					,
				[Site]						,
				[StubberUser]				,
				fu.[CentralIdx]				,
				[ZoneDesc]					,
				[ZoneGrpDesc]				,
				[CommentText]				,
				[CommentId]					,
				[CommentModifOn]			,
				[Comment_Rtf]				,
				ld.SITE_DIMENSION_SiteId	,
				ld.CentralLineId					,
				RcdIdx	
                FROM @QACLTaksRawdata d 
				JOIN [dbo].[FACT_UDPs] fu on fu.Idx = d.FACT_UDPs_Idx AND fu.VALUE='CL' AND  fu.SITE_DIMENSION_SiteId = @SiteId
				JOIN dbo.LINE_DIMENSION ld ON d.PLID = ld.PLId AND ld.SITE_DIMENSION_SiteId = @SiteId
) S ON (
						T.[SITE_DIMENSION_SiteId]		= s.SITE_DIMENSION_SiteId AND
						T.LINE_DIMENSION_CentralLineId	= s.CentralLineid AND
						T.RcdIdx						= s.RcdIdx	
	    )


	UPDATE [dbo].[Transfer_Parameter_Data]
		SET LastModifytime = ( SELECT MAX(ModifiedOn) FROM @QACLTaksRawdata )
	WHERE TableName = 'OpsDB_VariablesTasks_RawData'
	AND SiteId = @SiteId

RETURN
;
GO

GRANT EXEC ON TYPE::[dbo].[OpsDB_QA_CL_Data_Type]  TO [LocalUser]
GO

GRANT EXECUTE ON OBJECT ::[dbo].splocal_InsertQACLRawData  TO [LocalUser]
GO
